sudo: required
dist: trusty
language: cpp

notifications:
  email: false

 os:
  - linux
  - osx

compiler:
  - gcc
  - clang


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                      		               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew glfw3                                              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xorg-dev libglu1-mesa-dev libglew-dev libglfw2;sudo apt-get update ; git clone https://github.com/glfw/glfw.git ./glfw ; cd ./glfw ; git checkout latest ;cmake . -DBUILD_SHARED_LIBS=ON ; make ; sudo make install ; sudo ldconfig ; cd .. ; fi

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - mkdir build/
  - cd build/
  - cmake -DMACE_STATIC_LIBRARY=ON -DMACE_UNIT_TESTING=ON ..
  - make
  - ./MACE-Testing
