sudo: false
language: cpp

notifications:
  email: false

os:
  - linux
  
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backport #for newer cmake
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - mkdir build/
  - cd build/
  - cmake ..
  - make
  - cd bin/
  - ./MC-Testing
