sudo: required
language: cpp

notifications:
  email: false

os:
  - osx
  - linux
  
compiler:
  - gcc
  - clang
   
addons:
  apt:
    sources:
      -sourceline: 'ppa:ubuntu-toolchain-r-test'
    packages:
      - gcc4.8
      - g++4.8
      - clang
      - cmake

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - mkdir build/
  - cd build/
  - cmake ..
  - make
  - cd bin/
  - ./MC-Testing
