.TH "bug" 3 "Sun Apr 9 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBClass \fBmc::gfx::Font\fP \fP" 1c
\fBHorizontalAlignment::RIGHT\fP misses the last letter in the width calculation  
.IP "\fBClass \fBmc::gfx::Text\fP \fP" 1c
newline with vertical align doesnt really work  
.IP "\fBMember \fBmc::math::det\fP (const Matrix< T, N, N > &matrix)\fP" 1c
Array subscript out of range with matrices bigger than 2x2  
.IP "\fBMember \fBmc::math::inverse\fP (const Matrix< T, N, N > &matrix)\fP" 1c
Matrices bigger then 2x2 dont work  
.IP "\fBMember \fBmc::Matrix< T, W, H >::operator/\fP (const Matrix< T, W, H > &right) const \fP" 1c
Not finished  
.IP "\fBMember \fBmc::Matrix< T, W, H >::operator<<\fP (std::ostream &output, const Matrix< T, W, H > &m)\fP" 1c
the order is not retained exactly 
.PP

