.TH "mc" 3 "Wed Feb 1 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc \- Namespace for everything in \fBMACE\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBColors\fP"
.br
.RI "\fIContains various \fC\fBColor\fP\fP constants for common colors\&. \fP"
.ti -1c
.RI " \fBgfx\fP"
.br
.RI "\fINamespace containing classes used for Graphics in \fBMACE\fP\&. \fP"
.ti -1c
.RI " \fBMACE\fP"
.br
.RI "\fICore class of \fBMACE\fP, managing \fCModules\fP\&. \fP"
.ti -1c
.RI " \fBmath\fP"
.br
.RI "\fINamespace with various mathmatical functions\&. \fP"
.ti -1c
.RI " \fBos\fP"
.br
.RI "\fINamespace with functions related to the operating system like keyboard input, mouse, and windows\&. \fP"
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioModule\fP"
.br
.ti -1c
.RI "struct \fBBitField\fP"
.br
.RI "\fIWrapper class for a primitive type that allows for easy bit manipulation\&. \fP"
.ti -1c
.RI "struct \fBColor\fP"
.br
.RI "\fIRepresents a color in the RGBA space\&. \fP"
.ti -1c
.RI "class \fBException\fP"
.br
.RI "\fISuperclass that all exceptions in \fBMACE\fP extend\&. \fP"
.ti -1c
.RI "class \fBInclude\fP"
.br
.RI "\fISuperclass for classes that represent items that can be included via #include\&. \fP"
.ti -1c
.RI "class \fBIncludeDirectory\fP"
.br
.RI "\fIRepresents a directory on the disk from which you can include files from\&. \fP"
.ti -1c
.RI "class \fBIncludeString\fP"
.br
.RI "\fIRepresents a fake file, in which you can add include files that don't exist on the filesystem\&. \fP"
.ti -1c
.RI "struct \fBMacro\fP"
.br
.RI "\fIRepresents a \fC\fBMacro\fP\fP in code\&. \fP"
.ti -1c
.RI "struct \fBMatrix\fP"
.br
.RI "\fIA class representing a 2-dimensional matrix, and allows for math involving matrices\&. \fP"
.ti -1c
.RI "class \fBModule\fP"
.br
.RI "\fIAbstract class used for doing a task in \fBMACE\fP\&. \fP"
.ti -1c
.RI "class \fBPreprocessor\fP"
.br
.RI "\fICustomizable string preprocessor which follows ANSI-C preprocessor standard\&. \fP"
.ti -1c
.RI "class \fBSound\fP"
.br
.ti -1c
.RI "struct \fBTransformMatrix\fP"
.br
.RI "\fIMatrix-based class that allows for the easy creation and management of transformation matrices\&. \fP"
.ti -1c
.RI "struct \fBVector\fP"
.br
.RI "\fI1-dimensional vector class that supports mathmatical operations\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBByte\fP = std::uint8_t"
.br
.RI "\fIPrimitive type guaranteed to be equal to 8 bits (1 byte)\&. \fP"
.ti -1c
.RI "using \fBSize\fP = unsigned int"
.br
.RI "\fIType representing an object's size\&. \fP"
.ti -1c
.RI "using \fBIndex\fP = unsigned int"
.br
.RI "\fIType representing an index in an array\&. \fP"
.ti -1c
.RI "using \fBEnum\fP = unsigned int"
.br
.RI "\fIType representing an int-based enum (such as GL_* constants) \fP"
.ti -1c
.RI "typedef void(* \fBVoidFunctionPtr\fP) ()"
.br
.RI "\fIType representing a function that returns void and has no arguments\&. \fP"
.ti -1c
.RI "using \fBNullPointerException\fP = \fBException\fP"
.br
.RI "\fIThrown when a pointer is equal to NULL\&. \fP"
.ti -1c
.RI "using \fBAssertionError\fP = \fBException\fP"
.br
.RI "\fIThrown when an assertion fails\&. \fP"
.ti -1c
.RI "using \fBInitializationError\fP = \fBException\fP"
.br
.RI "\fIThrown when an object wasn't initializaed or initializtion failed\&. \fP"
.ti -1c
.RI "using \fBObjectNotFoundInArrayException\fP = \fBException\fP"
.br
.RI "\fIThrown when a function looks for an object, but doesn't find it\&. \fP"
.ti -1c
.RI "using \fBIndexOutOfBoundsException\fP = \fBException\fP"
.br
.RI "\fIThrown when an index is provided for an array, but it is outside the valid bounds of the array\&. \fP"
.ti -1c
.RI "using \fBArithmeticException\fP = \fBException\fP"
.br
.RI "\fIThrown when something goes wrong while doing math, like dividing by zero\&. \fP"
.ti -1c
.RI "template<typename T , Size N> using \fBMatrixRow\fP = \fBmc::Vector\fP< T, N >"
.br
.RI "\fIUsed in the \fC\fBMatrix\fP\fP class\&. \fP"
.ti -1c
.RI "using \fBVector1i\fP = \fBVector\fP< int, 1 >"
.br
.ti -1c
.RI "using \fBVector2i\fP = \fBVector\fP< int, 2 >"
.br
.ti -1c
.RI "using \fBVector3i\fP = \fBVector\fP< int, 3 >"
.br
.ti -1c
.RI "using \fBVector4i\fP = \fBVector\fP< int, 4 >"
.br
.ti -1c
.RI "using \fBVector5i\fP = \fBVector\fP< int, 5 >"
.br
.ti -1c
.RI "using \fBVector1ui\fP = \fBVector\fP< unsigned int, 1 >"
.br
.ti -1c
.RI "using \fBVector2ui\fP = \fBVector\fP< unsigned int, 2 >"
.br
.ti -1c
.RI "using \fBVector3ui\fP = \fBVector\fP< unsigned int, 3 >"
.br
.ti -1c
.RI "using \fBVector4ui\fP = \fBVector\fP< unsigned int, 4 >"
.br
.ti -1c
.RI "using \fBVector5ui\fP = \fBVector\fP< unsigned int, 5 >"
.br
.ti -1c
.RI "using \fBVector1si\fP = \fBVector\fP< signed int, 1 >"
.br
.ti -1c
.RI "using \fBVector2si\fP = \fBVector\fP< signed int, 2 >"
.br
.ti -1c
.RI "using \fBVector3si\fP = \fBVector\fP< signed int, 3 >"
.br
.ti -1c
.RI "using \fBVector4si\fP = \fBVector\fP< signed int, 4 >"
.br
.ti -1c
.RI "using \fBVector5si\fP = \fBVector\fP< signed int, 5 >"
.br
.ti -1c
.RI "using \fBVector1f\fP = \fBVector\fP< float, 1 >"
.br
.ti -1c
.RI "using \fBVector2f\fP = \fBVector\fP< float, 2 >"
.br
.ti -1c
.RI "using \fBVector3f\fP = \fBVector\fP< float, 3 >"
.br
.ti -1c
.RI "using \fBVector4f\fP = \fBVector\fP< float, 4 >"
.br
.ti -1c
.RI "using \fBVector5f\fP = \fBVector\fP< float, 5 >"
.br
.ti -1c
.RI "using \fBVector1d\fP = \fBVector\fP< double, 1 >"
.br
.ti -1c
.RI "using \fBVector2d\fP = \fBVector\fP< double, 2 >"
.br
.ti -1c
.RI "using \fBVector3d\fP = \fBVector\fP< double, 3 >"
.br
.ti -1c
.RI "using \fBVector4d\fP = \fBVector\fP< double, 4 >"
.br
.ti -1c
.RI "using \fBVector5d\fP = \fBVector\fP< double, 5 >"
.br
.ti -1c
.RI "using \fBVector1ld\fP = \fBVector\fP< long double, 1 >"
.br
.ti -1c
.RI "using \fBVector2ld\fP = \fBVector\fP< long double, 2 >"
.br
.ti -1c
.RI "using \fBVector3ld\fP = \fBVector\fP< long double, 3 >"
.br
.ti -1c
.RI "using \fBVector4ld\fP = \fBVector\fP< long double, 4 >"
.br
.ti -1c
.RI "using \fBVector5ld\fP = \fBVector\fP< long double, 5 >"
.br
.ti -1c
.RI "using \fBVector1s\fP = \fBVector\fP< short int, 1 >"
.br
.ti -1c
.RI "using \fBVector2s\fP = \fBVector\fP< short int, 2 >"
.br
.ti -1c
.RI "using \fBVector3s\fP = \fBVector\fP< short int, 3 >"
.br
.ti -1c
.RI "using \fBVector4s\fP = \fBVector\fP< short int, 4 >"
.br
.ti -1c
.RI "using \fBVector5s\fP = \fBVector\fP< short int, 5 >"
.br
.ti -1c
.RI "using \fBVector1us\fP = \fBVector\fP< unsigned short int, 1 >"
.br
.ti -1c
.RI "using \fBVector2us\fP = \fBVector\fP< unsigned short int, 2 >"
.br
.ti -1c
.RI "using \fBVector3us\fP = \fBVector\fP< unsigned short int, 3 >"
.br
.ti -1c
.RI "using \fBVector4us\fP = \fBVector\fP< unsigned short int, 4 >"
.br
.ti -1c
.RI "using \fBVector5us\fP = \fBVector\fP< unsigned short int, 5 >"
.br
.ti -1c
.RI "using \fBVector1ss\fP = \fBVector\fP< signed short int, 1 >"
.br
.ti -1c
.RI "using \fBVector2ss\fP = \fBVector\fP< signed short int, 2 >"
.br
.ti -1c
.RI "using \fBVector3ss\fP = \fBVector\fP< signed short int, 3 >"
.br
.ti -1c
.RI "using \fBVector4ss\fP = \fBVector\fP< signed short int, 4 >"
.br
.ti -1c
.RI "using \fBVector5ss\fP = \fBVector\fP< signed short int, 5 >"
.br
.ti -1c
.RI "using \fBVector1l\fP = \fBVector\fP< long int, 1 >"
.br
.ti -1c
.RI "using \fBVector2l\fP = \fBVector\fP< long int, 2 >"
.br
.ti -1c
.RI "using \fBVector3l\fP = \fBVector\fP< long int, 3 >"
.br
.ti -1c
.RI "using \fBVector4l\fP = \fBVector\fP< long int, 4 >"
.br
.ti -1c
.RI "using \fBVector5l\fP = \fBVector\fP< long int, 5 >"
.br
.ti -1c
.RI "using \fBVector1ul\fP = \fBVector\fP< unsigned long int, 1 >"
.br
.ti -1c
.RI "using \fBVector2ul\fP = \fBVector\fP< unsigned long int, 2 >"
.br
.ti -1c
.RI "using \fBVector3ul\fP = \fBVector\fP< unsigned long int, 3 >"
.br
.ti -1c
.RI "using \fBVector4ul\fP = \fBVector\fP< unsigned long int, 4 >"
.br
.ti -1c
.RI "using \fBVector5ul\fP = \fBVector\fP< unsigned long int, 5 >"
.br
.ti -1c
.RI "using \fBVector1sl\fP = \fBVector\fP< signed long int, 1 >"
.br
.ti -1c
.RI "using \fBVector2sl\fP = \fBVector\fP< signed long int, 2 >"
.br
.ti -1c
.RI "using \fBVector3sl\fP = \fBVector\fP< signed long int, 3 >"
.br
.ti -1c
.RI "using \fBVector4sl\fP = \fBVector\fP< signed long int, 4 >"
.br
.ti -1c
.RI "using \fBVector5sl\fP = \fBVector\fP< signed long int, 5 >"
.br
.ti -1c
.RI "using \fBVector1ll\fP = \fBVector\fP< long long int, 1 >"
.br
.ti -1c
.RI "using \fBVector2ll\fP = \fBVector\fP< long long int, 2 >"
.br
.ti -1c
.RI "using \fBVector3ll\fP = \fBVector\fP< long long int, 3 >"
.br
.ti -1c
.RI "using \fBVector4ll\fP = \fBVector\fP< long long int, 4 >"
.br
.ti -1c
.RI "using \fBVector5ll\fP = \fBVector\fP< long long int, 5 >"
.br
.ti -1c
.RI "using \fBVector1ull\fP = \fBVector\fP< unsigned long long int, 1 >"
.br
.ti -1c
.RI "using \fBVector2ull\fP = \fBVector\fP< unsigned long long int, 2 >"
.br
.ti -1c
.RI "using \fBVector3ull\fP = \fBVector\fP< unsigned long long int, 3 >"
.br
.ti -1c
.RI "using \fBVector4ull\fP = \fBVector\fP< unsigned long long int, 4 >"
.br
.ti -1c
.RI "using \fBVector5ull\fP = \fBVector\fP< unsigned long long int, 5 >"
.br
.ti -1c
.RI "using \fBVector1sll\fP = \fBVector\fP< signed long long int, 1 >"
.br
.ti -1c
.RI "using \fBVector2sll\fP = \fBVector\fP< signed long long int, 2 >"
.br
.ti -1c
.RI "using \fBVector3sll\fP = \fBVector\fP< signed long long int, 3 >"
.br
.ti -1c
.RI "using \fBVector4sll\fP = \fBVector\fP< signed long long int, 4 >"
.br
.ti -1c
.RI "using \fBVector5sll\fP = \fBVector\fP< signed long long int, 5 >"
.br
.ti -1c
.RI "using \fBVector1c\fP = \fBVector\fP< char, 1 >"
.br
.ti -1c
.RI "using \fBVector2c\fP = \fBVector\fP< char, 2 >"
.br
.ti -1c
.RI "using \fBVector3c\fP = \fBVector\fP< char, 3 >"
.br
.ti -1c
.RI "using \fBVector4c\fP = \fBVector\fP< char, 4 >"
.br
.ti -1c
.RI "using \fBVector5c\fP = \fBVector\fP< char, 5 >"
.br
.ti -1c
.RI "using \fBVector1uc\fP = \fBVector\fP< unsigned char, 1 >"
.br
.ti -1c
.RI "using \fBVector2uc\fP = \fBVector\fP< unsigned char, 2 >"
.br
.ti -1c
.RI "using \fBVector3uc\fP = \fBVector\fP< unsigned char, 3 >"
.br
.ti -1c
.RI "using \fBVector4uc\fP = \fBVector\fP< unsigned char, 4 >"
.br
.ti -1c
.RI "using \fBVector5uc\fP = \fBVector\fP< unsigned char, 5 >"
.br
.ti -1c
.RI "using \fBVector1sc\fP = \fBVector\fP< signed char, 1 >"
.br
.ti -1c
.RI "using \fBVector2sc\fP = \fBVector\fP< signed char, 2 >"
.br
.ti -1c
.RI "using \fBVector3sc\fP = \fBVector\fP< signed char, 3 >"
.br
.ti -1c
.RI "using \fBVector4sc\fP = \fBVector\fP< signed char, 4 >"
.br
.ti -1c
.RI "using \fBVector5sc\fP = \fBVector\fP< signed char, 5 >"
.br
.ti -1c
.RI "using \fBMatrix1i\fP = \fBMatrix\fP< int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2i\fP = \fBMatrix\fP< int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3i\fP = \fBMatrix\fP< int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4i\fP = \fBMatrix\fP< int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5i\fP = \fBMatrix\fP< int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3i\fP = \fBMatrix\fP< int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2i\fP = \fBMatrix\fP< int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4i\fP = \fBMatrix\fP< int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2i\fP = \fBMatrix\fP< int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5i\fP = \fBMatrix\fP< int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2i\fP = \fBMatrix\fP< int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4i\fP = \fBMatrix\fP< int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3i\fP = \fBMatrix\fP< int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5i\fP = \fBMatrix\fP< int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3i\fP = \fBMatrix\fP< int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5i\fP = \fBMatrix\fP< int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4i\fP = \fBMatrix\fP< int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1ui\fP = \fBMatrix\fP< unsigned int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2ui\fP = \fBMatrix\fP< unsigned int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3ui\fP = \fBMatrix\fP< unsigned int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4ui\fP = \fBMatrix\fP< unsigned int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5ui\fP = \fBMatrix\fP< unsigned int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3ui\fP = \fBMatrix\fP< unsigned int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2ui\fP = \fBMatrix\fP< unsigned int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4ui\fP = \fBMatrix\fP< unsigned int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2ui\fP = \fBMatrix\fP< unsigned int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5ui\fP = \fBMatrix\fP< unsigned int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2ui\fP = \fBMatrix\fP< unsigned int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4ui\fP = \fBMatrix\fP< unsigned int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3ui\fP = \fBMatrix\fP< unsigned int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5ui\fP = \fBMatrix\fP< unsigned int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3ui\fP = \fBMatrix\fP< unsigned int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5ui\fP = \fBMatrix\fP< unsigned int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4ui\fP = \fBMatrix\fP< unsigned int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1si\fP = \fBMatrix\fP< signed int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2si\fP = \fBMatrix\fP< signed int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3si\fP = \fBMatrix\fP< signed int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4si\fP = \fBMatrix\fP< signed int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5si\fP = \fBMatrix\fP< signed int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3si\fP = \fBMatrix\fP< signed int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2si\fP = \fBMatrix\fP< signed int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4si\fP = \fBMatrix\fP< signed int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2si\fP = \fBMatrix\fP< signed int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5si\fP = \fBMatrix\fP< signed int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2si\fP = \fBMatrix\fP< signed int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4si\fP = \fBMatrix\fP< signed int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3si\fP = \fBMatrix\fP< signed int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5si\fP = \fBMatrix\fP< signed int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3si\fP = \fBMatrix\fP< signed int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5si\fP = \fBMatrix\fP< signed int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4si\fP = \fBMatrix\fP< signed int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1f\fP = \fBMatrix\fP< float, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2f\fP = \fBMatrix\fP< float, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3f\fP = \fBMatrix\fP< float, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4f\fP = \fBMatrix\fP< float, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5f\fP = \fBMatrix\fP< float, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3f\fP = \fBMatrix\fP< float, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2f\fP = \fBMatrix\fP< float, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4f\fP = \fBMatrix\fP< float, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2f\fP = \fBMatrix\fP< float, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5f\fP = \fBMatrix\fP< float, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2f\fP = \fBMatrix\fP< float, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4f\fP = \fBMatrix\fP< float, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3f\fP = \fBMatrix\fP< float, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5f\fP = \fBMatrix\fP< float, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3f\fP = \fBMatrix\fP< float, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5f\fP = \fBMatrix\fP< float, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4f\fP = \fBMatrix\fP< float, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1d\fP = \fBMatrix\fP< double, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2d\fP = \fBMatrix\fP< double, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3d\fP = \fBMatrix\fP< double, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4d\fP = \fBMatrix\fP< double, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5d\fP = \fBMatrix\fP< double, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3d\fP = \fBMatrix\fP< double, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2d\fP = \fBMatrix\fP< double, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4d\fP = \fBMatrix\fP< double, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2d\fP = \fBMatrix\fP< double, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5d\fP = \fBMatrix\fP< double, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2d\fP = \fBMatrix\fP< double, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4d\fP = \fBMatrix\fP< double, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3d\fP = \fBMatrix\fP< double, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5d\fP = \fBMatrix\fP< double, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3d\fP = \fBMatrix\fP< double, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5d\fP = \fBMatrix\fP< double, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4d\fP = \fBMatrix\fP< double, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1ld\fP = \fBMatrix\fP< long double, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2ld\fP = \fBMatrix\fP< long double, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3ld\fP = \fBMatrix\fP< long double, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4ld\fP = \fBMatrix\fP< long double, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5ld\fP = \fBMatrix\fP< long double, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3ld\fP = \fBMatrix\fP< long double, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2ld\fP = \fBMatrix\fP< long double, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4ld\fP = \fBMatrix\fP< long double, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2ld\fP = \fBMatrix\fP< long double, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5ld\fP = \fBMatrix\fP< long double, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2ld\fP = \fBMatrix\fP< long double, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4ld\fP = \fBMatrix\fP< long double, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3ld\fP = \fBMatrix\fP< long double, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5ld\fP = \fBMatrix\fP< long double, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3ld\fP = \fBMatrix\fP< long double, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5ld\fP = \fBMatrix\fP< long double, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4ld\fP = \fBMatrix\fP< long double, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1s\fP = \fBMatrix\fP< short int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2s\fP = \fBMatrix\fP< short int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3s\fP = \fBMatrix\fP< short int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4s\fP = \fBMatrix\fP< short int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5s\fP = \fBMatrix\fP< short int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3s\fP = \fBMatrix\fP< short int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2s\fP = \fBMatrix\fP< short int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4s\fP = \fBMatrix\fP< short int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2s\fP = \fBMatrix\fP< short int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5s\fP = \fBMatrix\fP< short int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2s\fP = \fBMatrix\fP< short int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4s\fP = \fBMatrix\fP< short int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3s\fP = \fBMatrix\fP< short int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5s\fP = \fBMatrix\fP< short int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3s\fP = \fBMatrix\fP< short int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5s\fP = \fBMatrix\fP< short int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4s\fP = \fBMatrix\fP< short int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1us\fP = \fBMatrix\fP< unsigned short int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2us\fP = \fBMatrix\fP< unsigned short int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3us\fP = \fBMatrix\fP< unsigned short int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4us\fP = \fBMatrix\fP< unsigned short int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5us\fP = \fBMatrix\fP< unsigned short int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3us\fP = \fBMatrix\fP< unsigned short int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2us\fP = \fBMatrix\fP< unsigned short int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4us\fP = \fBMatrix\fP< unsigned short int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2us\fP = \fBMatrix\fP< unsigned short int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5us\fP = \fBMatrix\fP< unsigned short int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2us\fP = \fBMatrix\fP< unsigned short int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4us\fP = \fBMatrix\fP< unsigned short int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3us\fP = \fBMatrix\fP< unsigned short int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5us\fP = \fBMatrix\fP< unsigned short int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3us\fP = \fBMatrix\fP< unsigned short int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5us\fP = \fBMatrix\fP< unsigned short int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4us\fP = \fBMatrix\fP< unsigned short int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1ss\fP = \fBMatrix\fP< signed short int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2ss\fP = \fBMatrix\fP< signed short int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3ss\fP = \fBMatrix\fP< signed short int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4ss\fP = \fBMatrix\fP< signed short int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5ss\fP = \fBMatrix\fP< signed short int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3ss\fP = \fBMatrix\fP< signed short int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2ss\fP = \fBMatrix\fP< signed short int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4ss\fP = \fBMatrix\fP< signed short int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2ss\fP = \fBMatrix\fP< signed short int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5ss\fP = \fBMatrix\fP< signed short int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2ss\fP = \fBMatrix\fP< signed short int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4ss\fP = \fBMatrix\fP< signed short int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3ss\fP = \fBMatrix\fP< signed short int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5ss\fP = \fBMatrix\fP< signed short int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3ss\fP = \fBMatrix\fP< signed short int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5ss\fP = \fBMatrix\fP< signed short int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4ss\fP = \fBMatrix\fP< signed short int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1l\fP = \fBMatrix\fP< long int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2l\fP = \fBMatrix\fP< long int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3l\fP = \fBMatrix\fP< long int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4l\fP = \fBMatrix\fP< long int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5l\fP = \fBMatrix\fP< long int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3l\fP = \fBMatrix\fP< long int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2l\fP = \fBMatrix\fP< long int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4l\fP = \fBMatrix\fP< long int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2l\fP = \fBMatrix\fP< long int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5l\fP = \fBMatrix\fP< long int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2l\fP = \fBMatrix\fP< long int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4l\fP = \fBMatrix\fP< long int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3l\fP = \fBMatrix\fP< long int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5l\fP = \fBMatrix\fP< long int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3l\fP = \fBMatrix\fP< long int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5l\fP = \fBMatrix\fP< long int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4l\fP = \fBMatrix\fP< long int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1ul\fP = \fBMatrix\fP< unsigned long int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2ul\fP = \fBMatrix\fP< unsigned long int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3ul\fP = \fBMatrix\fP< unsigned long int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4ul\fP = \fBMatrix\fP< unsigned long int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5ul\fP = \fBMatrix\fP< unsigned long int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3ul\fP = \fBMatrix\fP< unsigned long int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2ul\fP = \fBMatrix\fP< unsigned long int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4ul\fP = \fBMatrix\fP< unsigned long int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2ul\fP = \fBMatrix\fP< unsigned long int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5ul\fP = \fBMatrix\fP< unsigned long int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2ul\fP = \fBMatrix\fP< unsigned long int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4ul\fP = \fBMatrix\fP< unsigned long int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3ul\fP = \fBMatrix\fP< unsigned long int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5ul\fP = \fBMatrix\fP< unsigned long int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3ul\fP = \fBMatrix\fP< unsigned long int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5ul\fP = \fBMatrix\fP< unsigned long int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4ul\fP = \fBMatrix\fP< unsigned long int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1sl\fP = \fBMatrix\fP< signed long int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2sl\fP = \fBMatrix\fP< signed long int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3sl\fP = \fBMatrix\fP< signed long int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4sl\fP = \fBMatrix\fP< signed long int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5sl\fP = \fBMatrix\fP< signed long int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3sl\fP = \fBMatrix\fP< signed long int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2sl\fP = \fBMatrix\fP< signed long int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4sl\fP = \fBMatrix\fP< signed long int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2sl\fP = \fBMatrix\fP< signed long int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5sl\fP = \fBMatrix\fP< signed long int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2sl\fP = \fBMatrix\fP< signed long int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4sl\fP = \fBMatrix\fP< signed long int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3sl\fP = \fBMatrix\fP< signed long int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5sl\fP = \fBMatrix\fP< signed long int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3sl\fP = \fBMatrix\fP< signed long int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5sl\fP = \fBMatrix\fP< signed long int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4sl\fP = \fBMatrix\fP< signed long int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1ll\fP = \fBMatrix\fP< long long int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2ll\fP = \fBMatrix\fP< long long int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3ll\fP = \fBMatrix\fP< long long int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4ll\fP = \fBMatrix\fP< long long int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5ll\fP = \fBMatrix\fP< long long int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3ll\fP = \fBMatrix\fP< long long int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2ll\fP = \fBMatrix\fP< long long int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4ll\fP = \fBMatrix\fP< long long int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2ll\fP = \fBMatrix\fP< long long int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5ll\fP = \fBMatrix\fP< long long int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2ll\fP = \fBMatrix\fP< long long int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4ll\fP = \fBMatrix\fP< long long int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3ll\fP = \fBMatrix\fP< long long int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5ll\fP = \fBMatrix\fP< long long int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3ll\fP = \fBMatrix\fP< long long int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5ll\fP = \fBMatrix\fP< long long int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4ll\fP = \fBMatrix\fP< long long int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1ull\fP = \fBMatrix\fP< unsigned long long int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2ull\fP = \fBMatrix\fP< unsigned long long int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3ull\fP = \fBMatrix\fP< unsigned long long int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4ull\fP = \fBMatrix\fP< unsigned long long int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5ull\fP = \fBMatrix\fP< unsigned long long int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3ull\fP = \fBMatrix\fP< unsigned long long int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2ull\fP = \fBMatrix\fP< unsigned long long int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4ull\fP = \fBMatrix\fP< unsigned long long int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2ull\fP = \fBMatrix\fP< unsigned long long int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5ull\fP = \fBMatrix\fP< unsigned long long int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2ull\fP = \fBMatrix\fP< unsigned long long int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4ull\fP = \fBMatrix\fP< unsigned long long int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3ull\fP = \fBMatrix\fP< unsigned long long int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5ull\fP = \fBMatrix\fP< unsigned long long int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3ull\fP = \fBMatrix\fP< unsigned long long int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5ull\fP = \fBMatrix\fP< unsigned long long int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4ull\fP = \fBMatrix\fP< unsigned long long int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1sll\fP = \fBMatrix\fP< signed long long int, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2sll\fP = \fBMatrix\fP< signed long long int, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3sll\fP = \fBMatrix\fP< signed long long int, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4sll\fP = \fBMatrix\fP< signed long long int, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5sll\fP = \fBMatrix\fP< signed long long int, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3sll\fP = \fBMatrix\fP< signed long long int, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2sll\fP = \fBMatrix\fP< signed long long int, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4sll\fP = \fBMatrix\fP< signed long long int, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2sll\fP = \fBMatrix\fP< signed long long int, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5sll\fP = \fBMatrix\fP< signed long long int, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2sll\fP = \fBMatrix\fP< signed long long int, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4sll\fP = \fBMatrix\fP< signed long long int, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3sll\fP = \fBMatrix\fP< signed long long int, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5sll\fP = \fBMatrix\fP< signed long long int, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3sll\fP = \fBMatrix\fP< signed long long int, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5sll\fP = \fBMatrix\fP< signed long long int, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4sll\fP = \fBMatrix\fP< signed long long int, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1c\fP = \fBMatrix\fP< char, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2c\fP = \fBMatrix\fP< char, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3c\fP = \fBMatrix\fP< char, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4c\fP = \fBMatrix\fP< char, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5c\fP = \fBMatrix\fP< char, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3c\fP = \fBMatrix\fP< char, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2c\fP = \fBMatrix\fP< char, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4c\fP = \fBMatrix\fP< char, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2c\fP = \fBMatrix\fP< char, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5c\fP = \fBMatrix\fP< char, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2c\fP = \fBMatrix\fP< char, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4c\fP = \fBMatrix\fP< char, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3c\fP = \fBMatrix\fP< char, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5c\fP = \fBMatrix\fP< char, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3c\fP = \fBMatrix\fP< char, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5c\fP = \fBMatrix\fP< char, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4c\fP = \fBMatrix\fP< char, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1uc\fP = \fBMatrix\fP< unsigned char, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2uc\fP = \fBMatrix\fP< unsigned char, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3uc\fP = \fBMatrix\fP< unsigned char, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4uc\fP = \fBMatrix\fP< unsigned char, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5uc\fP = \fBMatrix\fP< unsigned char, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3uc\fP = \fBMatrix\fP< unsigned char, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2uc\fP = \fBMatrix\fP< unsigned char, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4uc\fP = \fBMatrix\fP< unsigned char, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2uc\fP = \fBMatrix\fP< unsigned char, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5uc\fP = \fBMatrix\fP< unsigned char, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2uc\fP = \fBMatrix\fP< unsigned char, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4uc\fP = \fBMatrix\fP< unsigned char, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3uc\fP = \fBMatrix\fP< unsigned char, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5uc\fP = \fBMatrix\fP< unsigned char, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3uc\fP = \fBMatrix\fP< unsigned char, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5uc\fP = \fBMatrix\fP< unsigned char, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4uc\fP = \fBMatrix\fP< unsigned char, 5, 4 >"
.br
.ti -1c
.RI "using \fBMatrix1sc\fP = \fBMatrix\fP< signed char, 1, 1 >"
.br
.ti -1c
.RI "using \fBMatrix2sc\fP = \fBMatrix\fP< signed char, 2, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3sc\fP = \fBMatrix\fP< signed char, 3, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4sc\fP = \fBMatrix\fP< signed char, 4, 4 >"
.br
.ti -1c
.RI "using \fBMatrix5sc\fP = \fBMatrix\fP< signed char, 5, 5 >"
.br
.ti -1c
.RI "using \fBMatrix2x3sc\fP = \fBMatrix\fP< signed char, 2, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x2sc\fP = \fBMatrix\fP< signed char, 3, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x4sc\fP = \fBMatrix\fP< signed char, 2, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x2sc\fP = \fBMatrix\fP< signed char, 4, 2 >"
.br
.ti -1c
.RI "using \fBMatrix2x5sc\fP = \fBMatrix\fP< signed char, 2, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x2sc\fP = \fBMatrix\fP< signed char, 5, 2 >"
.br
.ti -1c
.RI "using \fBMatrix3x4sc\fP = \fBMatrix\fP< signed char, 3, 4 >"
.br
.ti -1c
.RI "using \fBMatrix4x3sc\fP = \fBMatrix\fP< signed char, 4, 3 >"
.br
.ti -1c
.RI "using \fBMatrix3x5sc\fP = \fBMatrix\fP< signed char, 3, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x3sc\fP = \fBMatrix\fP< signed char, 5, 3 >"
.br
.ti -1c
.RI "using \fBMatrix4x5sc\fP = \fBMatrix\fP< signed char, 4, 5 >"
.br
.ti -1c
.RI "using \fBMatrix5x4sc\fP = \fBMatrix\fP< signed char, 5, 4 >"
.br
.ti -1c
.RI "using \fBPreprocessorException\fP = \fBException\fP"
.br
.RI "\fI\fC\fBException\fP\fP thrown when a syntax error is encountered, or #error is called\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , Size N> \fBVector\fP< T, N > \fBoperator*=\fP (const \fBVector\fP< T, N > &v, const \fBMatrix\fP< T, N, N > &m)"
.br
.ti -1c
.RI "template<typename T , Size N> \fBVector\fP< T, N > \fBoperator*\fP (const \fBVector\fP< T, N > &v, const \fBMatrix\fP< T, N, N > &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Namespace for everything in \fBMACE\fP\&. 

This includes constants, typedefs, tests, classes, and variables\&. 
.PP
Preproccessor definitions will start with \fCMACE_\fP and \fCMACE_INCLUDED\fP will be defined to equal \fCtrue\fP if \fBMACE\fP is included\&. 
.SH "Typedef Documentation"
.PP 
.SS "using \fBmc::ArithmeticException\fP = typedef \fBException\fP"

.PP
Thrown when something goes wrong while doing math, like dividing by zero\&. 
.PP
Definition at line 163 of file Constants\&.h\&.
.SS "using \fBmc::AssertionError\fP = typedef \fBException\fP"

.PP
Thrown when an assertion fails\&. 
.PP
\fBSee also:\fP
.RS 4
\fBMACE::assertModule(std::string)\fP 
.RE
.PP

.PP
Definition at line 145 of file Constants\&.h\&.
.SS "using \fBmc::Byte\fP = typedef std::uint8_t"

.PP
Primitive type guaranteed to be equal to 8 bits (1 byte)\&. The definition here is for clarity\&. 
.PP
\fBSee also:\fP
.RS 4
\fBVoidFunctionPtr\fP 
.PP
\fBIndex\fP 
.PP
\fBEnum\fP 
.PP
\fBSize\fP 
.RE
.PP

.PP
Definition at line 55 of file Constants\&.h\&.
.SS "using \fBmc::Enum\fP = typedef unsigned int"

.PP
Type representing an int-based enum (such as GL_* constants) 
.PP
\fBSee also:\fP
.RS 4
\fBIndex\fP 
.PP
\fBVoidFunctionPtr\fP 
.PP
\fBSize\fP 
.RE
.PP

.PP
Definition at line 104 of file Constants\&.h\&.
.SS "using \fBmc::Index\fP = typedef unsigned int"

.PP
Type representing an index in an array\&. The definition here is for clarity, and it makes code more obvious and self-documenting\&. Imagine this: 
.PP
.nf
removeObject(unsigned int)

.fi
.PP
 or 
.PP
.nf
getObject(unsigned int)

.fi
.PP
 \fCunsigned int\fP is ambigious! What if the object is an \fCunsigned int\fP? With this definition, it becomes much more clear: 
.PP
.nf
removeObject(Index)

getObject(Index)

.fi
.PP
.PP
\fBSee also:\fP
.RS 4
\fBSize\fP 
.PP
\fBVoidFunctionPtr\fP 
.PP
\fBEnum\fP 
.RE
.PP

.PP
Definition at line 97 of file Constants\&.h\&.
.SS "using \fBmc::IndexOutOfBoundsException\fP = typedef \fBException\fP"

.PP
Thrown when an index is provided for an array, but it is outside the valid bounds of the array\&. 
.PP
Definition at line 159 of file Constants\&.h\&.
.SS "using \fBmc::InitializationError\fP = typedef \fBException\fP"

.PP
Thrown when an object wasn't initializaed or initializtion failed\&. 
.PP
Definition at line 150 of file Constants\&.h\&.
.SS "using \fBmc::Matrix1c\fP = typedef \fBMatrix\fP< char, 1, 1 >"

.PP
Definition at line 368 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1d\fP = typedef \fBMatrix\fP< double, 1, 1 >"

.PP
Definition at line 181 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1f\fP = typedef \fBMatrix\fP< float, 1, 1 >"

.PP
Definition at line 164 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1i\fP = typedef \fBMatrix\fP< int, 1, 1 >"

.PP
Definition at line 113 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1l\fP = typedef \fBMatrix\fP< long int, 1, 1 >"

.PP
Definition at line 266 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1ld\fP = typedef \fBMatrix\fP< long double, 1, 1 >"

.PP
Definition at line 198 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1ll\fP = typedef \fBMatrix\fP< long long int, 1, 1 >"

.PP
Definition at line 317 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1s\fP = typedef \fBMatrix\fP< short int, 1, 1 >"

.PP
Definition at line 215 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1sc\fP = typedef \fBMatrix\fP< signed char, 1, 1 >"

.PP
Definition at line 402 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1si\fP = typedef \fBMatrix\fP< signed int, 1, 1 >"

.PP
Definition at line 147 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1sl\fP = typedef \fBMatrix\fP< signed long int, 1, 1 >"

.PP
Definition at line 300 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1sll\fP = typedef \fBMatrix\fP< signed long long int, 1, 1 >"

.PP
Definition at line 351 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1ss\fP = typedef \fBMatrix\fP< signed short int, 1, 1 >"

.PP
Definition at line 249 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1uc\fP = typedef \fBMatrix\fP< unsigned char, 1, 1 >"

.PP
Definition at line 385 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1ui\fP = typedef \fBMatrix\fP< unsigned int, 1, 1 >"

.PP
Definition at line 130 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1ul\fP = typedef \fBMatrix\fP< unsigned long int, 1, 1 >"

.PP
Definition at line 283 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1ull\fP = typedef \fBMatrix\fP< unsigned long long int, 1, 1 >"

.PP
Definition at line 334 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix1us\fP = typedef \fBMatrix\fP< unsigned short int, 1, 1 >"

.PP
Definition at line 232 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2c\fP = typedef \fBMatrix\fP< char, 2, 2 >"

.PP
Definition at line 369 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2d\fP = typedef \fBMatrix\fP< double, 2, 2 >"

.PP
Definition at line 182 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2f\fP = typedef \fBMatrix\fP< float, 2, 2 >"

.PP
Definition at line 165 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2i\fP = typedef \fBMatrix\fP< int, 2, 2 >"

.PP
Definition at line 114 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2l\fP = typedef \fBMatrix\fP< long int, 2, 2 >"

.PP
Definition at line 267 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2ld\fP = typedef \fBMatrix\fP< long double, 2, 2 >"

.PP
Definition at line 199 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2ll\fP = typedef \fBMatrix\fP< long long int, 2, 2 >"

.PP
Definition at line 318 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2s\fP = typedef \fBMatrix\fP< short int, 2, 2 >"

.PP
Definition at line 216 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2sc\fP = typedef \fBMatrix\fP< signed char, 2, 2 >"

.PP
Definition at line 403 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2si\fP = typedef \fBMatrix\fP< signed int, 2, 2 >"

.PP
Definition at line 148 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2sl\fP = typedef \fBMatrix\fP< signed long int, 2, 2 >"

.PP
Definition at line 301 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2sll\fP = typedef \fBMatrix\fP< signed long long int, 2, 2 >"

.PP
Definition at line 352 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2ss\fP = typedef \fBMatrix\fP< signed short int, 2, 2 >"

.PP
Definition at line 250 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2uc\fP = typedef \fBMatrix\fP< unsigned char, 2, 2 >"

.PP
Definition at line 386 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2ui\fP = typedef \fBMatrix\fP< unsigned int, 2, 2 >"

.PP
Definition at line 131 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2ul\fP = typedef \fBMatrix\fP< unsigned long int, 2, 2 >"

.PP
Definition at line 284 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2ull\fP = typedef \fBMatrix\fP< unsigned long long int, 2, 2 >"

.PP
Definition at line 335 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2us\fP = typedef \fBMatrix\fP< unsigned short int, 2, 2 >"

.PP
Definition at line 233 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3c\fP = typedef \fBMatrix\fP< char, 2, 3 >"

.PP
Definition at line 373 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3d\fP = typedef \fBMatrix\fP< double, 2, 3 >"

.PP
Definition at line 186 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3f\fP = typedef \fBMatrix\fP< float, 2, 3 >"

.PP
Definition at line 169 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3i\fP = typedef \fBMatrix\fP< int, 2, 3 >"

.PP
Definition at line 118 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3l\fP = typedef \fBMatrix\fP< long int, 2, 3 >"

.PP
Definition at line 271 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3ld\fP = typedef \fBMatrix\fP< long double, 2, 3 >"

.PP
Definition at line 203 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3ll\fP = typedef \fBMatrix\fP< long long int, 2, 3 >"

.PP
Definition at line 322 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3s\fP = typedef \fBMatrix\fP< short int, 2, 3 >"

.PP
Definition at line 220 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3sc\fP = typedef \fBMatrix\fP< signed char, 2, 3 >"

.PP
Definition at line 407 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3si\fP = typedef \fBMatrix\fP< signed int, 2, 3 >"

.PP
Definition at line 152 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3sl\fP = typedef \fBMatrix\fP< signed long int, 2, 3 >"

.PP
Definition at line 305 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3sll\fP = typedef \fBMatrix\fP< signed long long int, 2, 3 >"

.PP
Definition at line 356 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3ss\fP = typedef \fBMatrix\fP< signed short int, 2, 3 >"

.PP
Definition at line 254 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3uc\fP = typedef \fBMatrix\fP< unsigned char, 2, 3 >"

.PP
Definition at line 390 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3ui\fP = typedef \fBMatrix\fP< unsigned int, 2, 3 >"

.PP
Definition at line 135 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3ul\fP = typedef \fBMatrix\fP< unsigned long int, 2, 3 >"

.PP
Definition at line 288 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3ull\fP = typedef \fBMatrix\fP< unsigned long long int, 2, 3 >"

.PP
Definition at line 339 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x3us\fP = typedef \fBMatrix\fP< unsigned short int, 2, 3 >"

.PP
Definition at line 237 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4c\fP = typedef \fBMatrix\fP< char, 2, 4 >"

.PP
Definition at line 375 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4d\fP = typedef \fBMatrix\fP< double, 2, 4 >"

.PP
Definition at line 188 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4f\fP = typedef \fBMatrix\fP< float, 2, 4 >"

.PP
Definition at line 171 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4i\fP = typedef \fBMatrix\fP< int, 2, 4 >"

.PP
Definition at line 120 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4l\fP = typedef \fBMatrix\fP< long int, 2, 4 >"

.PP
Definition at line 273 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4ld\fP = typedef \fBMatrix\fP< long double, 2, 4 >"

.PP
Definition at line 205 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4ll\fP = typedef \fBMatrix\fP< long long int, 2, 4 >"

.PP
Definition at line 324 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4s\fP = typedef \fBMatrix\fP< short int, 2, 4 >"

.PP
Definition at line 222 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4sc\fP = typedef \fBMatrix\fP< signed char, 2, 4 >"

.PP
Definition at line 409 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4si\fP = typedef \fBMatrix\fP< signed int, 2, 4 >"

.PP
Definition at line 154 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4sl\fP = typedef \fBMatrix\fP< signed long int, 2, 4 >"

.PP
Definition at line 307 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4sll\fP = typedef \fBMatrix\fP< signed long long int, 2, 4 >"

.PP
Definition at line 358 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4ss\fP = typedef \fBMatrix\fP< signed short int, 2, 4 >"

.PP
Definition at line 256 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4uc\fP = typedef \fBMatrix\fP< unsigned char, 2, 4 >"

.PP
Definition at line 392 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4ui\fP = typedef \fBMatrix\fP< unsigned int, 2, 4 >"

.PP
Definition at line 137 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4ul\fP = typedef \fBMatrix\fP< unsigned long int, 2, 4 >"

.PP
Definition at line 290 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4ull\fP = typedef \fBMatrix\fP< unsigned long long int, 2, 4 >"

.PP
Definition at line 341 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x4us\fP = typedef \fBMatrix\fP< unsigned short int, 2, 4 >"

.PP
Definition at line 239 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5c\fP = typedef \fBMatrix\fP< char, 2, 5 >"

.PP
Definition at line 377 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5d\fP = typedef \fBMatrix\fP< double, 2, 5 >"

.PP
Definition at line 190 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5f\fP = typedef \fBMatrix\fP< float, 2, 5 >"

.PP
Definition at line 173 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5i\fP = typedef \fBMatrix\fP< int, 2, 5 >"

.PP
Definition at line 122 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5l\fP = typedef \fBMatrix\fP< long int, 2, 5 >"

.PP
Definition at line 275 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5ld\fP = typedef \fBMatrix\fP< long double, 2, 5 >"

.PP
Definition at line 207 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5ll\fP = typedef \fBMatrix\fP< long long int, 2, 5 >"

.PP
Definition at line 326 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5s\fP = typedef \fBMatrix\fP< short int, 2, 5 >"

.PP
Definition at line 224 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5sc\fP = typedef \fBMatrix\fP< signed char, 2, 5 >"

.PP
Definition at line 411 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5si\fP = typedef \fBMatrix\fP< signed int, 2, 5 >"

.PP
Definition at line 156 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5sl\fP = typedef \fBMatrix\fP< signed long int, 2, 5 >"

.PP
Definition at line 309 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5sll\fP = typedef \fBMatrix\fP< signed long long int, 2, 5 >"

.PP
Definition at line 360 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5ss\fP = typedef \fBMatrix\fP< signed short int, 2, 5 >"

.PP
Definition at line 258 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5uc\fP = typedef \fBMatrix\fP< unsigned char, 2, 5 >"

.PP
Definition at line 394 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5ui\fP = typedef \fBMatrix\fP< unsigned int, 2, 5 >"

.PP
Definition at line 139 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5ul\fP = typedef \fBMatrix\fP< unsigned long int, 2, 5 >"

.PP
Definition at line 292 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5ull\fP = typedef \fBMatrix\fP< unsigned long long int, 2, 5 >"

.PP
Definition at line 343 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix2x5us\fP = typedef \fBMatrix\fP< unsigned short int, 2, 5 >"

.PP
Definition at line 241 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3c\fP = typedef \fBMatrix\fP< char, 3, 3 >"

.PP
Definition at line 370 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3d\fP = typedef \fBMatrix\fP< double, 3, 3 >"

.PP
Definition at line 183 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3f\fP = typedef \fBMatrix\fP< float, 3, 3 >"

.PP
Definition at line 166 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3i\fP = typedef \fBMatrix\fP< int, 3, 3 >"

.PP
Definition at line 115 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3l\fP = typedef \fBMatrix\fP< long int, 3, 3 >"

.PP
Definition at line 268 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3ld\fP = typedef \fBMatrix\fP< long double, 3, 3 >"

.PP
Definition at line 200 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3ll\fP = typedef \fBMatrix\fP< long long int, 3, 3 >"

.PP
Definition at line 319 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3s\fP = typedef \fBMatrix\fP< short int, 3, 3 >"

.PP
Definition at line 217 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3sc\fP = typedef \fBMatrix\fP< signed char, 3, 3 >"

.PP
Definition at line 404 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3si\fP = typedef \fBMatrix\fP< signed int, 3, 3 >"

.PP
Definition at line 149 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3sl\fP = typedef \fBMatrix\fP< signed long int, 3, 3 >"

.PP
Definition at line 302 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3sll\fP = typedef \fBMatrix\fP< signed long long int, 3, 3 >"

.PP
Definition at line 353 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3ss\fP = typedef \fBMatrix\fP< signed short int, 3, 3 >"

.PP
Definition at line 251 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3uc\fP = typedef \fBMatrix\fP< unsigned char, 3, 3 >"

.PP
Definition at line 387 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3ui\fP = typedef \fBMatrix\fP< unsigned int, 3, 3 >"

.PP
Definition at line 132 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3ul\fP = typedef \fBMatrix\fP< unsigned long int, 3, 3 >"

.PP
Definition at line 285 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3ull\fP = typedef \fBMatrix\fP< unsigned long long int, 3, 3 >"

.PP
Definition at line 336 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3us\fP = typedef \fBMatrix\fP< unsigned short int, 3, 3 >"

.PP
Definition at line 234 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2c\fP = typedef \fBMatrix\fP< char, 3, 2 >"

.PP
Definition at line 374 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2d\fP = typedef \fBMatrix\fP< double, 3, 2 >"

.PP
Definition at line 187 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2f\fP = typedef \fBMatrix\fP< float, 3, 2 >"

.PP
Definition at line 170 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2i\fP = typedef \fBMatrix\fP< int, 3, 2 >"

.PP
Definition at line 119 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2l\fP = typedef \fBMatrix\fP< long int, 3, 2 >"

.PP
Definition at line 272 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2ld\fP = typedef \fBMatrix\fP< long double, 3, 2 >"

.PP
Definition at line 204 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2ll\fP = typedef \fBMatrix\fP< long long int, 3, 2 >"

.PP
Definition at line 323 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2s\fP = typedef \fBMatrix\fP< short int, 3, 2 >"

.PP
Definition at line 221 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2sc\fP = typedef \fBMatrix\fP< signed char, 3, 2 >"

.PP
Definition at line 408 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2si\fP = typedef \fBMatrix\fP< signed int, 3, 2 >"

.PP
Definition at line 153 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2sl\fP = typedef \fBMatrix\fP< signed long int, 3, 2 >"

.PP
Definition at line 306 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2sll\fP = typedef \fBMatrix\fP< signed long long int, 3, 2 >"

.PP
Definition at line 357 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2ss\fP = typedef \fBMatrix\fP< signed short int, 3, 2 >"

.PP
Definition at line 255 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2uc\fP = typedef \fBMatrix\fP< unsigned char, 3, 2 >"

.PP
Definition at line 391 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2ui\fP = typedef \fBMatrix\fP< unsigned int, 3, 2 >"

.PP
Definition at line 136 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2ul\fP = typedef \fBMatrix\fP< unsigned long int, 3, 2 >"

.PP
Definition at line 289 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2ull\fP = typedef \fBMatrix\fP< unsigned long long int, 3, 2 >"

.PP
Definition at line 340 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x2us\fP = typedef \fBMatrix\fP< unsigned short int, 3, 2 >"

.PP
Definition at line 238 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4c\fP = typedef \fBMatrix\fP< char, 3, 4 >"

.PP
Definition at line 379 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4d\fP = typedef \fBMatrix\fP< double, 3, 4 >"

.PP
Definition at line 192 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4f\fP = typedef \fBMatrix\fP< float, 3, 4 >"

.PP
Definition at line 175 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4i\fP = typedef \fBMatrix\fP< int, 3, 4 >"

.PP
Definition at line 124 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4l\fP = typedef \fBMatrix\fP< long int, 3, 4 >"

.PP
Definition at line 277 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4ld\fP = typedef \fBMatrix\fP< long double, 3, 4 >"

.PP
Definition at line 209 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4ll\fP = typedef \fBMatrix\fP< long long int, 3, 4 >"

.PP
Definition at line 328 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4s\fP = typedef \fBMatrix\fP< short int, 3, 4 >"

.PP
Definition at line 226 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4sc\fP = typedef \fBMatrix\fP< signed char, 3, 4 >"

.PP
Definition at line 413 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4si\fP = typedef \fBMatrix\fP< signed int, 3, 4 >"

.PP
Definition at line 158 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4sl\fP = typedef \fBMatrix\fP< signed long int, 3, 4 >"

.PP
Definition at line 311 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4sll\fP = typedef \fBMatrix\fP< signed long long int, 3, 4 >"

.PP
Definition at line 362 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4ss\fP = typedef \fBMatrix\fP< signed short int, 3, 4 >"

.PP
Definition at line 260 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4uc\fP = typedef \fBMatrix\fP< unsigned char, 3, 4 >"

.PP
Definition at line 396 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4ui\fP = typedef \fBMatrix\fP< unsigned int, 3, 4 >"

.PP
Definition at line 141 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4ul\fP = typedef \fBMatrix\fP< unsigned long int, 3, 4 >"

.PP
Definition at line 294 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4ull\fP = typedef \fBMatrix\fP< unsigned long long int, 3, 4 >"

.PP
Definition at line 345 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x4us\fP = typedef \fBMatrix\fP< unsigned short int, 3, 4 >"

.PP
Definition at line 243 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5c\fP = typedef \fBMatrix\fP< char, 3, 5 >"

.PP
Definition at line 381 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5d\fP = typedef \fBMatrix\fP< double, 3, 5 >"

.PP
Definition at line 194 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5f\fP = typedef \fBMatrix\fP< float, 3, 5 >"

.PP
Definition at line 177 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5i\fP = typedef \fBMatrix\fP< int, 3, 5 >"

.PP
Definition at line 126 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5l\fP = typedef \fBMatrix\fP< long int, 3, 5 >"

.PP
Definition at line 279 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5ld\fP = typedef \fBMatrix\fP< long double, 3, 5 >"

.PP
Definition at line 211 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5ll\fP = typedef \fBMatrix\fP< long long int, 3, 5 >"

.PP
Definition at line 330 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5s\fP = typedef \fBMatrix\fP< short int, 3, 5 >"

.PP
Definition at line 228 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5sc\fP = typedef \fBMatrix\fP< signed char, 3, 5 >"

.PP
Definition at line 415 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5si\fP = typedef \fBMatrix\fP< signed int, 3, 5 >"

.PP
Definition at line 160 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5sl\fP = typedef \fBMatrix\fP< signed long int, 3, 5 >"

.PP
Definition at line 313 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5sll\fP = typedef \fBMatrix\fP< signed long long int, 3, 5 >"

.PP
Definition at line 364 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5ss\fP = typedef \fBMatrix\fP< signed short int, 3, 5 >"

.PP
Definition at line 262 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5uc\fP = typedef \fBMatrix\fP< unsigned char, 3, 5 >"

.PP
Definition at line 398 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5ui\fP = typedef \fBMatrix\fP< unsigned int, 3, 5 >"

.PP
Definition at line 143 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5ul\fP = typedef \fBMatrix\fP< unsigned long int, 3, 5 >"

.PP
Definition at line 296 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5ull\fP = typedef \fBMatrix\fP< unsigned long long int, 3, 5 >"

.PP
Definition at line 347 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix3x5us\fP = typedef \fBMatrix\fP< unsigned short int, 3, 5 >"

.PP
Definition at line 245 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4c\fP = typedef \fBMatrix\fP< char, 4, 4 >"

.PP
Definition at line 371 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4d\fP = typedef \fBMatrix\fP< double, 4, 4 >"

.PP
Definition at line 184 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4f\fP = typedef \fBMatrix\fP< float, 4, 4 >"

.PP
Definition at line 167 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4i\fP = typedef \fBMatrix\fP< int, 4, 4 >"

.PP
Definition at line 116 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4l\fP = typedef \fBMatrix\fP< long int, 4, 4 >"

.PP
Definition at line 269 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4ld\fP = typedef \fBMatrix\fP< long double, 4, 4 >"

.PP
Definition at line 201 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4ll\fP = typedef \fBMatrix\fP< long long int, 4, 4 >"

.PP
Definition at line 320 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4s\fP = typedef \fBMatrix\fP< short int, 4, 4 >"

.PP
Definition at line 218 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4sc\fP = typedef \fBMatrix\fP< signed char, 4, 4 >"

.PP
Definition at line 405 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4si\fP = typedef \fBMatrix\fP< signed int, 4, 4 >"

.PP
Definition at line 150 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4sl\fP = typedef \fBMatrix\fP< signed long int, 4, 4 >"

.PP
Definition at line 303 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4sll\fP = typedef \fBMatrix\fP< signed long long int, 4, 4 >"

.PP
Definition at line 354 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4ss\fP = typedef \fBMatrix\fP< signed short int, 4, 4 >"

.PP
Definition at line 252 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4uc\fP = typedef \fBMatrix\fP< unsigned char, 4, 4 >"

.PP
Definition at line 388 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4ui\fP = typedef \fBMatrix\fP< unsigned int, 4, 4 >"

.PP
Definition at line 133 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4ul\fP = typedef \fBMatrix\fP< unsigned long int, 4, 4 >"

.PP
Definition at line 286 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4ull\fP = typedef \fBMatrix\fP< unsigned long long int, 4, 4 >"

.PP
Definition at line 337 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4us\fP = typedef \fBMatrix\fP< unsigned short int, 4, 4 >"

.PP
Definition at line 235 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2c\fP = typedef \fBMatrix\fP< char, 4, 2 >"

.PP
Definition at line 376 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2d\fP = typedef \fBMatrix\fP< double, 4, 2 >"

.PP
Definition at line 189 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2f\fP = typedef \fBMatrix\fP< float, 4, 2 >"

.PP
Definition at line 172 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2i\fP = typedef \fBMatrix\fP< int, 4, 2 >"

.PP
Definition at line 121 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2l\fP = typedef \fBMatrix\fP< long int, 4, 2 >"

.PP
Definition at line 274 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2ld\fP = typedef \fBMatrix\fP< long double, 4, 2 >"

.PP
Definition at line 206 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2ll\fP = typedef \fBMatrix\fP< long long int, 4, 2 >"

.PP
Definition at line 325 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2s\fP = typedef \fBMatrix\fP< short int, 4, 2 >"

.PP
Definition at line 223 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2sc\fP = typedef \fBMatrix\fP< signed char, 4, 2 >"

.PP
Definition at line 410 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2si\fP = typedef \fBMatrix\fP< signed int, 4, 2 >"

.PP
Definition at line 155 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2sl\fP = typedef \fBMatrix\fP< signed long int, 4, 2 >"

.PP
Definition at line 308 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2sll\fP = typedef \fBMatrix\fP< signed long long int, 4, 2 >"

.PP
Definition at line 359 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2ss\fP = typedef \fBMatrix\fP< signed short int, 4, 2 >"

.PP
Definition at line 257 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2uc\fP = typedef \fBMatrix\fP< unsigned char, 4, 2 >"

.PP
Definition at line 393 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2ui\fP = typedef \fBMatrix\fP< unsigned int, 4, 2 >"

.PP
Definition at line 138 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2ul\fP = typedef \fBMatrix\fP< unsigned long int, 4, 2 >"

.PP
Definition at line 291 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2ull\fP = typedef \fBMatrix\fP< unsigned long long int, 4, 2 >"

.PP
Definition at line 342 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x2us\fP = typedef \fBMatrix\fP< unsigned short int, 4, 2 >"

.PP
Definition at line 240 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3c\fP = typedef \fBMatrix\fP< char, 4, 3 >"

.PP
Definition at line 380 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3d\fP = typedef \fBMatrix\fP< double, 4, 3 >"

.PP
Definition at line 193 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3f\fP = typedef \fBMatrix\fP< float, 4, 3 >"

.PP
Definition at line 176 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3i\fP = typedef \fBMatrix\fP< int, 4, 3 >"

.PP
Definition at line 125 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3l\fP = typedef \fBMatrix\fP< long int, 4, 3 >"

.PP
Definition at line 278 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3ld\fP = typedef \fBMatrix\fP< long double, 4, 3 >"

.PP
Definition at line 210 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3ll\fP = typedef \fBMatrix\fP< long long int, 4, 3 >"

.PP
Definition at line 329 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3s\fP = typedef \fBMatrix\fP< short int, 4, 3 >"

.PP
Definition at line 227 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3sc\fP = typedef \fBMatrix\fP< signed char, 4, 3 >"

.PP
Definition at line 414 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3si\fP = typedef \fBMatrix\fP< signed int, 4, 3 >"

.PP
Definition at line 159 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3sl\fP = typedef \fBMatrix\fP< signed long int, 4, 3 >"

.PP
Definition at line 312 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3sll\fP = typedef \fBMatrix\fP< signed long long int, 4, 3 >"

.PP
Definition at line 363 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3ss\fP = typedef \fBMatrix\fP< signed short int, 4, 3 >"

.PP
Definition at line 261 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3uc\fP = typedef \fBMatrix\fP< unsigned char, 4, 3 >"

.PP
Definition at line 397 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3ui\fP = typedef \fBMatrix\fP< unsigned int, 4, 3 >"

.PP
Definition at line 142 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3ul\fP = typedef \fBMatrix\fP< unsigned long int, 4, 3 >"

.PP
Definition at line 295 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3ull\fP = typedef \fBMatrix\fP< unsigned long long int, 4, 3 >"

.PP
Definition at line 346 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x3us\fP = typedef \fBMatrix\fP< unsigned short int, 4, 3 >"

.PP
Definition at line 244 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5c\fP = typedef \fBMatrix\fP< char, 4, 5 >"

.PP
Definition at line 383 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5d\fP = typedef \fBMatrix\fP< double, 4, 5 >"

.PP
Definition at line 196 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5f\fP = typedef \fBMatrix\fP< float, 4, 5 >"

.PP
Definition at line 179 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5i\fP = typedef \fBMatrix\fP< int, 4, 5 >"

.PP
Definition at line 128 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5l\fP = typedef \fBMatrix\fP< long int, 4, 5 >"

.PP
Definition at line 281 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5ld\fP = typedef \fBMatrix\fP< long double, 4, 5 >"

.PP
Definition at line 213 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5ll\fP = typedef \fBMatrix\fP< long long int, 4, 5 >"

.PP
Definition at line 332 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5s\fP = typedef \fBMatrix\fP< short int, 4, 5 >"

.PP
Definition at line 230 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5sc\fP = typedef \fBMatrix\fP< signed char, 4, 5 >"

.PP
Definition at line 417 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5si\fP = typedef \fBMatrix\fP< signed int, 4, 5 >"

.PP
Definition at line 162 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5sl\fP = typedef \fBMatrix\fP< signed long int, 4, 5 >"

.PP
Definition at line 315 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5sll\fP = typedef \fBMatrix\fP< signed long long int, 4, 5 >"

.PP
Definition at line 366 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5ss\fP = typedef \fBMatrix\fP< signed short int, 4, 5 >"

.PP
Definition at line 264 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5uc\fP = typedef \fBMatrix\fP< unsigned char, 4, 5 >"

.PP
Definition at line 400 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5ui\fP = typedef \fBMatrix\fP< unsigned int, 4, 5 >"

.PP
Definition at line 145 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5ul\fP = typedef \fBMatrix\fP< unsigned long int, 4, 5 >"

.PP
Definition at line 298 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5ull\fP = typedef \fBMatrix\fP< unsigned long long int, 4, 5 >"

.PP
Definition at line 349 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix4x5us\fP = typedef \fBMatrix\fP< unsigned short int, 4, 5 >"

.PP
Definition at line 247 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5c\fP = typedef \fBMatrix\fP< char, 5, 5 >"

.PP
Definition at line 372 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5d\fP = typedef \fBMatrix\fP< double, 5, 5 >"

.PP
Definition at line 185 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5f\fP = typedef \fBMatrix\fP< float, 5, 5 >"

.PP
Definition at line 168 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5i\fP = typedef \fBMatrix\fP< int, 5, 5 >"

.PP
Definition at line 117 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5l\fP = typedef \fBMatrix\fP< long int, 5, 5 >"

.PP
Definition at line 270 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5ld\fP = typedef \fBMatrix\fP< long double, 5, 5 >"

.PP
Definition at line 202 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5ll\fP = typedef \fBMatrix\fP< long long int, 5, 5 >"

.PP
Definition at line 321 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5s\fP = typedef \fBMatrix\fP< short int, 5, 5 >"

.PP
Definition at line 219 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5sc\fP = typedef \fBMatrix\fP< signed char, 5, 5 >"

.PP
Definition at line 406 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5si\fP = typedef \fBMatrix\fP< signed int, 5, 5 >"

.PP
Definition at line 151 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5sl\fP = typedef \fBMatrix\fP< signed long int, 5, 5 >"

.PP
Definition at line 304 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5sll\fP = typedef \fBMatrix\fP< signed long long int, 5, 5 >"

.PP
Definition at line 355 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5ss\fP = typedef \fBMatrix\fP< signed short int, 5, 5 >"

.PP
Definition at line 253 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5uc\fP = typedef \fBMatrix\fP< unsigned char, 5, 5 >"

.PP
Definition at line 389 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5ui\fP = typedef \fBMatrix\fP< unsigned int, 5, 5 >"

.PP
Definition at line 134 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5ul\fP = typedef \fBMatrix\fP< unsigned long int, 5, 5 >"

.PP
Definition at line 287 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5ull\fP = typedef \fBMatrix\fP< unsigned long long int, 5, 5 >"

.PP
Definition at line 338 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5us\fP = typedef \fBMatrix\fP< unsigned short int, 5, 5 >"

.PP
Definition at line 236 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2c\fP = typedef \fBMatrix\fP< char, 5, 2 >"

.PP
Definition at line 378 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2d\fP = typedef \fBMatrix\fP< double, 5, 2 >"

.PP
Definition at line 191 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2f\fP = typedef \fBMatrix\fP< float, 5, 2 >"

.PP
Definition at line 174 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2i\fP = typedef \fBMatrix\fP< int, 5, 2 >"

.PP
Definition at line 123 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2l\fP = typedef \fBMatrix\fP< long int, 5, 2 >"

.PP
Definition at line 276 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2ld\fP = typedef \fBMatrix\fP< long double, 5, 2 >"

.PP
Definition at line 208 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2ll\fP = typedef \fBMatrix\fP< long long int, 5, 2 >"

.PP
Definition at line 327 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2s\fP = typedef \fBMatrix\fP< short int, 5, 2 >"

.PP
Definition at line 225 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2sc\fP = typedef \fBMatrix\fP< signed char, 5, 2 >"

.PP
Definition at line 412 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2si\fP = typedef \fBMatrix\fP< signed int, 5, 2 >"

.PP
Definition at line 157 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2sl\fP = typedef \fBMatrix\fP< signed long int, 5, 2 >"

.PP
Definition at line 310 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2sll\fP = typedef \fBMatrix\fP< signed long long int, 5, 2 >"

.PP
Definition at line 361 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2ss\fP = typedef \fBMatrix\fP< signed short int, 5, 2 >"

.PP
Definition at line 259 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2uc\fP = typedef \fBMatrix\fP< unsigned char, 5, 2 >"

.PP
Definition at line 395 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2ui\fP = typedef \fBMatrix\fP< unsigned int, 5, 2 >"

.PP
Definition at line 140 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2ul\fP = typedef \fBMatrix\fP< unsigned long int, 5, 2 >"

.PP
Definition at line 293 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2ull\fP = typedef \fBMatrix\fP< unsigned long long int, 5, 2 >"

.PP
Definition at line 344 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x2us\fP = typedef \fBMatrix\fP< unsigned short int, 5, 2 >"

.PP
Definition at line 242 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3c\fP = typedef \fBMatrix\fP< char, 5, 3 >"

.PP
Definition at line 382 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3d\fP = typedef \fBMatrix\fP< double, 5, 3 >"

.PP
Definition at line 195 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3f\fP = typedef \fBMatrix\fP< float, 5, 3 >"

.PP
Definition at line 178 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3i\fP = typedef \fBMatrix\fP< int, 5, 3 >"

.PP
Definition at line 127 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3l\fP = typedef \fBMatrix\fP< long int, 5, 3 >"

.PP
Definition at line 280 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3ld\fP = typedef \fBMatrix\fP< long double, 5, 3 >"

.PP
Definition at line 212 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3ll\fP = typedef \fBMatrix\fP< long long int, 5, 3 >"

.PP
Definition at line 331 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3s\fP = typedef \fBMatrix\fP< short int, 5, 3 >"

.PP
Definition at line 229 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3sc\fP = typedef \fBMatrix\fP< signed char, 5, 3 >"

.PP
Definition at line 416 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3si\fP = typedef \fBMatrix\fP< signed int, 5, 3 >"

.PP
Definition at line 161 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3sl\fP = typedef \fBMatrix\fP< signed long int, 5, 3 >"

.PP
Definition at line 314 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3sll\fP = typedef \fBMatrix\fP< signed long long int, 5, 3 >"

.PP
Definition at line 365 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3ss\fP = typedef \fBMatrix\fP< signed short int, 5, 3 >"

.PP
Definition at line 263 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3uc\fP = typedef \fBMatrix\fP< unsigned char, 5, 3 >"

.PP
Definition at line 399 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3ui\fP = typedef \fBMatrix\fP< unsigned int, 5, 3 >"

.PP
Definition at line 144 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3ul\fP = typedef \fBMatrix\fP< unsigned long int, 5, 3 >"

.PP
Definition at line 297 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3ull\fP = typedef \fBMatrix\fP< unsigned long long int, 5, 3 >"

.PP
Definition at line 348 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x3us\fP = typedef \fBMatrix\fP< unsigned short int, 5, 3 >"

.PP
Definition at line 246 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4c\fP = typedef \fBMatrix\fP< char, 5, 4 >"

.PP
Definition at line 384 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4d\fP = typedef \fBMatrix\fP< double, 5, 4 >"

.PP
Definition at line 197 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4f\fP = typedef \fBMatrix\fP< float, 5, 4 >"

.PP
Definition at line 180 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4i\fP = typedef \fBMatrix\fP< int, 5, 4 >"

.PP
Definition at line 129 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4l\fP = typedef \fBMatrix\fP< long int, 5, 4 >"

.PP
Definition at line 282 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4ld\fP = typedef \fBMatrix\fP< long double, 5, 4 >"

.PP
Definition at line 214 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4ll\fP = typedef \fBMatrix\fP< long long int, 5, 4 >"

.PP
Definition at line 333 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4s\fP = typedef \fBMatrix\fP< short int, 5, 4 >"

.PP
Definition at line 231 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4sc\fP = typedef \fBMatrix\fP< signed char, 5, 4 >"

.PP
Definition at line 418 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4si\fP = typedef \fBMatrix\fP< signed int, 5, 4 >"

.PP
Definition at line 163 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4sl\fP = typedef \fBMatrix\fP< signed long int, 5, 4 >"

.PP
Definition at line 316 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4sll\fP = typedef \fBMatrix\fP< signed long long int, 5, 4 >"

.PP
Definition at line 367 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4ss\fP = typedef \fBMatrix\fP< signed short int, 5, 4 >"

.PP
Definition at line 265 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4uc\fP = typedef \fBMatrix\fP< unsigned char, 5, 4 >"

.PP
Definition at line 401 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4ui\fP = typedef \fBMatrix\fP< unsigned int, 5, 4 >"

.PP
Definition at line 146 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4ul\fP = typedef \fBMatrix\fP< unsigned long int, 5, 4 >"

.PP
Definition at line 299 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4ull\fP = typedef \fBMatrix\fP< unsigned long long int, 5, 4 >"

.PP
Definition at line 350 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Matrix5x4us\fP = typedef \fBMatrix\fP< unsigned short int, 5, 4 >"

.PP
Definition at line 248 of file MatrixTypes\&.h\&.
.SS "template<typename T , Size N> using \fBmc::MatrixRow\fP = typedef \fBmc::Vector\fP<T, N>"

.PP
Used in the \fC\fBMatrix\fP\fP class\&. Defined for clarity for when you iterate over a \fC\fBMatrix\fP\&.\fP 
.PP
\fBSee also:\fP
.RS 4
\fBMatrix\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP What data type the row is made of 
.br
\fIN\fP The width of the row 
.RE
.PP

.PP
Definition at line 24 of file Matrix\&.h\&.
.SS "using \fBmc::NullPointerException\fP = typedef \fBException\fP"

.PP
Thrown when a pointer is equal to NULL\&. 
.PP
Definition at line 138 of file Constants\&.h\&.
.SS "using \fBmc::ObjectNotFoundInArrayException\fP = typedef \fBException\fP"

.PP
Thrown when a function looks for an object, but doesn't find it\&. 
.PP
Definition at line 155 of file Constants\&.h\&.
.SS "using \fBmc::PreprocessorException\fP = typedef \fBException\fP"

.PP
\fC\fBException\fP\fP thrown when a syntax error is encountered, or #error is called\&. The filename and line number will be in message\&. 
.PP
Definition at line 25 of file Preprocessor\&.h\&.
.SS "using \fBmc::Size\fP = typedef unsigned int"

.PP
Type representing an object's size\&. The definition here is for clarity, as it makes code more self documenting\&. Imagine this: 
.PP
.nf
unsigned int getSize()

.fi
.PP
 By using this definition, that code becomes: 
.PP
.nf
Size getSize()

.fi
.PP
 Not only is it shorter, but it makes it more obvious, making documentation easier\&. 
.PP
\fBSee also:\fP
.RS 4
\fBIndex\fP 
.PP
\fBEnum\fP 
.PP
\fBVoidFunctionPtr\fP 
.RE
.PP

.PP
Definition at line 73 of file Constants\&.h\&.
.SS "using \fBmc::Vector1c\fP = typedef \fBVector\fP< char, 1 >"

.PP
Definition at line 96 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1d\fP = typedef \fBVector\fP< double, 1 >"

.PP
Definition at line 41 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1f\fP = typedef \fBVector\fP< float, 1 >"

.PP
Definition at line 36 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1i\fP = typedef \fBVector\fP< int, 1 >"

.PP
Definition at line 21 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1l\fP = typedef \fBVector\fP< long int, 1 >"

.PP
Definition at line 66 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1ld\fP = typedef \fBVector\fP< long double, 1 >"

.PP
Definition at line 46 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1ll\fP = typedef \fBVector\fP< long long int, 1 >"

.PP
Definition at line 81 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1s\fP = typedef \fBVector\fP< short int, 1 >"

.PP
Definition at line 51 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1sc\fP = typedef \fBVector\fP< signed char, 1 >"

.PP
Definition at line 106 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1si\fP = typedef \fBVector\fP< signed int, 1 >"

.PP
Definition at line 31 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1sl\fP = typedef \fBVector\fP< signed long int, 1 >"

.PP
Definition at line 76 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1sll\fP = typedef \fBVector\fP< signed long long int, 1 >"

.PP
Definition at line 91 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1ss\fP = typedef \fBVector\fP< signed short int, 1 >"

.PP
Definition at line 61 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1uc\fP = typedef \fBVector\fP< unsigned char, 1 >"

.PP
Definition at line 101 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1ui\fP = typedef \fBVector\fP< unsigned int, 1 >"

.PP
Definition at line 26 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1ul\fP = typedef \fBVector\fP< unsigned long int, 1 >"

.PP
Definition at line 71 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1ull\fP = typedef \fBVector\fP< unsigned long long int, 1 >"

.PP
Definition at line 86 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector1us\fP = typedef \fBVector\fP< unsigned short int, 1 >"

.PP
Definition at line 56 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2c\fP = typedef \fBVector\fP< char, 2 >"

.PP
Definition at line 97 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2d\fP = typedef \fBVector\fP< double, 2 >"

.PP
Definition at line 42 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2f\fP = typedef \fBVector\fP< float, 2 >"

.PP
Definition at line 37 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2i\fP = typedef \fBVector\fP< int, 2 >"

.PP
Definition at line 22 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2l\fP = typedef \fBVector\fP< long int, 2 >"

.PP
Definition at line 67 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2ld\fP = typedef \fBVector\fP< long double, 2 >"

.PP
Definition at line 47 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2ll\fP = typedef \fBVector\fP< long long int, 2 >"

.PP
Definition at line 82 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2s\fP = typedef \fBVector\fP< short int, 2 >"

.PP
Definition at line 52 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2sc\fP = typedef \fBVector\fP< signed char, 2 >"

.PP
Definition at line 107 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2si\fP = typedef \fBVector\fP< signed int, 2 >"

.PP
Definition at line 32 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2sl\fP = typedef \fBVector\fP< signed long int, 2 >"

.PP
Definition at line 77 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2sll\fP = typedef \fBVector\fP< signed long long int, 2 >"

.PP
Definition at line 92 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2ss\fP = typedef \fBVector\fP< signed short int, 2 >"

.PP
Definition at line 62 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2uc\fP = typedef \fBVector\fP< unsigned char, 2 >"

.PP
Definition at line 102 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2ui\fP = typedef \fBVector\fP< unsigned int, 2 >"

.PP
Definition at line 27 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2ul\fP = typedef \fBVector\fP< unsigned long int, 2 >"

.PP
Definition at line 72 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2ull\fP = typedef \fBVector\fP< unsigned long long int, 2 >"

.PP
Definition at line 87 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector2us\fP = typedef \fBVector\fP< unsigned short int, 2 >"

.PP
Definition at line 57 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3c\fP = typedef \fBVector\fP< char, 3 >"

.PP
Definition at line 98 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3d\fP = typedef \fBVector\fP< double, 3 >"

.PP
Definition at line 43 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3f\fP = typedef \fBVector\fP< float, 3 >"

.PP
Definition at line 38 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3i\fP = typedef \fBVector\fP< int, 3 >"

.PP
Definition at line 23 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3l\fP = typedef \fBVector\fP< long int, 3 >"

.PP
Definition at line 68 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3ld\fP = typedef \fBVector\fP< long double, 3 >"

.PP
Definition at line 48 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3ll\fP = typedef \fBVector\fP< long long int, 3 >"

.PP
Definition at line 83 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3s\fP = typedef \fBVector\fP< short int, 3 >"

.PP
Definition at line 53 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3sc\fP = typedef \fBVector\fP< signed char, 3 >"

.PP
Definition at line 108 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3si\fP = typedef \fBVector\fP< signed int, 3 >"

.PP
Definition at line 33 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3sl\fP = typedef \fBVector\fP< signed long int, 3 >"

.PP
Definition at line 78 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3sll\fP = typedef \fBVector\fP< signed long long int, 3 >"

.PP
Definition at line 93 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3ss\fP = typedef \fBVector\fP< signed short int, 3 >"

.PP
Definition at line 63 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3uc\fP = typedef \fBVector\fP< unsigned char, 3 >"

.PP
Definition at line 103 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3ui\fP = typedef \fBVector\fP< unsigned int, 3 >"

.PP
Definition at line 28 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3ul\fP = typedef \fBVector\fP< unsigned long int, 3 >"

.PP
Definition at line 73 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3ull\fP = typedef \fBVector\fP< unsigned long long int, 3 >"

.PP
Definition at line 88 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector3us\fP = typedef \fBVector\fP< unsigned short int, 3 >"

.PP
Definition at line 58 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4c\fP = typedef \fBVector\fP< char, 4 >"

.PP
Definition at line 99 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4d\fP = typedef \fBVector\fP< double, 4 >"

.PP
Definition at line 44 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4f\fP = typedef \fBVector\fP< float, 4 >"

.PP
Definition at line 39 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4i\fP = typedef \fBVector\fP< int, 4 >"

.PP
Definition at line 24 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4l\fP = typedef \fBVector\fP< long int, 4 >"

.PP
Definition at line 69 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4ld\fP = typedef \fBVector\fP< long double, 4 >"

.PP
Definition at line 49 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4ll\fP = typedef \fBVector\fP< long long int, 4 >"

.PP
Definition at line 84 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4s\fP = typedef \fBVector\fP< short int, 4 >"

.PP
Definition at line 54 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4sc\fP = typedef \fBVector\fP< signed char, 4 >"

.PP
Definition at line 109 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4si\fP = typedef \fBVector\fP< signed int, 4 >"

.PP
Definition at line 34 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4sl\fP = typedef \fBVector\fP< signed long int, 4 >"

.PP
Definition at line 79 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4sll\fP = typedef \fBVector\fP< signed long long int, 4 >"

.PP
Definition at line 94 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4ss\fP = typedef \fBVector\fP< signed short int, 4 >"

.PP
Definition at line 64 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4uc\fP = typedef \fBVector\fP< unsigned char, 4 >"

.PP
Definition at line 104 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4ui\fP = typedef \fBVector\fP< unsigned int, 4 >"

.PP
Definition at line 29 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4ul\fP = typedef \fBVector\fP< unsigned long int, 4 >"

.PP
Definition at line 74 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4ull\fP = typedef \fBVector\fP< unsigned long long int, 4 >"

.PP
Definition at line 89 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector4us\fP = typedef \fBVector\fP< unsigned short int, 4 >"

.PP
Definition at line 59 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5c\fP = typedef \fBVector\fP< char, 5 >"

.PP
Definition at line 100 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5d\fP = typedef \fBVector\fP< double, 5 >"

.PP
Definition at line 45 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5f\fP = typedef \fBVector\fP< float, 5 >"

.PP
Definition at line 40 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5i\fP = typedef \fBVector\fP< int, 5 >"

.PP
Definition at line 25 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5l\fP = typedef \fBVector\fP< long int, 5 >"

.PP
Definition at line 70 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5ld\fP = typedef \fBVector\fP< long double, 5 >"

.PP
Definition at line 50 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5ll\fP = typedef \fBVector\fP< long long int, 5 >"

.PP
Definition at line 85 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5s\fP = typedef \fBVector\fP< short int, 5 >"

.PP
Definition at line 55 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5sc\fP = typedef \fBVector\fP< signed char, 5 >"

.PP
Definition at line 110 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5si\fP = typedef \fBVector\fP< signed int, 5 >"

.PP
Definition at line 35 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5sl\fP = typedef \fBVector\fP< signed long int, 5 >"

.PP
Definition at line 80 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5sll\fP = typedef \fBVector\fP< signed long long int, 5 >"

.PP
Definition at line 95 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5ss\fP = typedef \fBVector\fP< signed short int, 5 >"

.PP
Definition at line 65 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5uc\fP = typedef \fBVector\fP< unsigned char, 5 >"

.PP
Definition at line 105 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5ui\fP = typedef \fBVector\fP< unsigned int, 5 >"

.PP
Definition at line 30 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5ul\fP = typedef \fBVector\fP< unsigned long int, 5 >"

.PP
Definition at line 75 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5ull\fP = typedef \fBVector\fP< unsigned long long int, 5 >"

.PP
Definition at line 90 of file MatrixTypes\&.h\&.
.SS "using \fBmc::Vector5us\fP = typedef \fBVector\fP< unsigned short int, 5 >"

.PP
Definition at line 60 of file MatrixTypes\&.h\&.
.SS "typedef void(* mc::VoidFunctionPtr) ()"

.PP
Type representing a function that returns void and has no arguments\&. Created for clarity and for use in callbacks 
.PP
\fBSee also:\fP
.RS 4
\fBIndex\fP 
.PP
\fBSize\fP 
.PP
\fBEnum\fP 
.RE
.PP

.PP
Definition at line 114 of file Constants\&.h\&.
.SH "Function Documentation"
.PP 
.SS "template<typename T , Size N> \fBVector\fP<T, N> mc::operator* (const \fBVector\fP< T, N > & v, const \fBMatrix\fP< T, N, N > & m)"

.PP
Definition at line 514 of file Matrix\&.h\&.
.SS "template<typename T , Size N> \fBVector\fP<T, N> mc::operator*= (const \fBVector\fP< T, N > & v, const \fBMatrix\fP< T, N, N > & m)"

.PP
Definition at line 509 of file Matrix\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
