.TH "mc::AudioModule" 3 "Sat Jan 14 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::AudioModule \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Audio\&.h>\fP
.PP
Inherits \fBmc::Module\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 42 of file Audio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
