.TH "mc::Colors" 3 "Sat Dec 31 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::Colors \- Contains various \fC\fBColor\fP\fP constants for common colors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBColor\fP \fBRED\fP = \fBColor\fP(255, 0, 0)"
.br
.RI "\fIConstant \fC\fBColor\fP\fP value for easy access to common colors\&. \fP"
.ti -1c
.RI "const \fBColor\fP \fBGREEN\fP = \fBColor\fP(0, 255, 0)"
.br
.ti -1c
.RI "const \fBColor\fP \fBDARK_BLUE\fP = \fBColor\fP(0, 0, 255)"
.br
.ti -1c
.RI "const \fBColor\fP \fBCYAN\fP = \fBColor\fP(0, 255, 255)"
.br
.ti -1c
.RI "const \fBColor\fP \fBLIGHT_BLUE\fP = \fBColor\fP(50, 200, 255)"
.br
.ti -1c
.RI "const \fBColor\fP \fBDARK_RED\fP = \fBColor\fP(150, 0, 0)"
.br
.ti -1c
.RI "const \fBColor\fP \fBDARK_GREEN\fP = \fBColor\fP(0, 150, 0)"
.br
.ti -1c
.RI "const \fBColor\fP \fBPURPLE\fP = \fBColor\fP(100, 0, 255)"
.br
.ti -1c
.RI "const \fBColor\fP \fBMAGENTA\fP = \fBColor\fP(255, 0, 255)"
.br
.ti -1c
.RI "const \fBColor\fP \fBWHITE\fP = \fBColor\fP(255, 255, 255)"
.br
.ti -1c
.RI "const \fBColor\fP \fBBLACK\fP = \fBColor\fP(0, 0, 0)"
.br
.ti -1c
.RI "const \fBColor\fP \fBYELLOW\fP = \fBColor\fP(255, 255, 0)"
.br
.ti -1c
.RI "const \fBColor\fP \fBDARK_GRAY\fP = \fBColor\fP(100, 100, 100)"
.br
.ti -1c
.RI "const \fBColor\fP \fBLIGHT_GRAY\fP = \fBColor\fP(200, 200, 200)"
.br
.ti -1c
.RI "const \fBColor\fP \fBORANGE\fP = \fBColor\fP(255, 125, 0)"
.br
.ti -1c
.RI "const \fBColor\fP \fBGRAY\fP = \fBColor\fP(150, 150, 150)"
.br
.ti -1c
.RI "const \fBColor\fP \fBDARK_ORANGE\fP = \fBColor\fP(255, 100, 0)"
.br
.ti -1c
.RI "const \fBColor\fP \fBLIGHT_ORANGE\fP = \fBColor\fP(255, 150, 0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains various \fC\fBColor\fP\fP constants for common colors\&. 
.SH "Variable Documentation"
.PP 
.SS "const \fBColor\fP mc::Colors::BLACK = \fBColor\fP(0, 0, 0)"

.PP
Definition at line 253 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::CYAN = \fBColor\fP(0, 255, 255)"

.PP
Definition at line 249 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::DARK_BLUE = \fBColor\fP(0, 0, 255)"

.PP
Definition at line 249 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::DARK_GRAY = \fBColor\fP(100, 100, 100)"

.PP
Definition at line 254 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::DARK_GREEN = \fBColor\fP(0, 150, 0)"

.PP
Definition at line 251 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::DARK_ORANGE = \fBColor\fP(255, 100, 0)"

.PP
Definition at line 256 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::DARK_RED = \fBColor\fP(150, 0, 0)"

.PP
Definition at line 250 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::GRAY = \fBColor\fP(150, 150, 150)"

.PP
Definition at line 255 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::GREEN = \fBColor\fP(0, 255, 0)"

.PP
Definition at line 248 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::LIGHT_BLUE = \fBColor\fP(50, 200, 255)"

.PP
Definition at line 250 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::LIGHT_GRAY = \fBColor\fP(200, 200, 200)"

.PP
Definition at line 254 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::LIGHT_ORANGE = \fBColor\fP(255, 150, 0)"

.PP
Definition at line 256 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::MAGENTA = \fBColor\fP(255, 0, 255)"

.PP
Definition at line 252 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::ORANGE = \fBColor\fP(255, 125, 0)"

.PP
Definition at line 255 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::PURPLE = \fBColor\fP(100, 0, 255)"

.PP
Definition at line 251 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::RED = \fBColor\fP(255, 0, 0)"

.PP
Constant \fC\fBColor\fP\fP value for easy access to common colors\&. 
.PP
Definition at line 248 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::WHITE = \fBColor\fP(255, 255, 255)"

.PP
Definition at line 252 of file Color\&.h\&.
.SS "const \fBColor\fP mc::Colors::YELLOW = \fBColor\fP(255, 255, 0)"

.PP
Definition at line 253 of file Color\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
