.TH "mc::DynamicLibrary" 3 "Sat Apr 8 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::DynamicLibrary \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DynamicLibrary\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~DynamicLibrary\fP ()"
.br
.ti -1c
.RI "\fBDynamicLibrary\fP ()"
.br
.ti -1c
.RI "\fBDynamicLibrary\fP (const std::string &path)"
.br
.ti -1c
.RI "\fBDynamicLibrary\fP (const char *path)"
.br
.ti -1c
.RI "void \fBinit\fP (const std::string &path)"
.br
.ti -1c
.RI "void \fBinit\fP (const char *path)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void * \fBgetFunction\fP (const std::string &name)"
.br
.ti -1c
.RI "void * \fBgetFunction\fP (const char *name)"
.br
.ti -1c
.RI "void * \fBoperator[]\fP (const char *name)"
.br
.ti -1c
.RI "void * \fBoperator[]\fP (const std::string &name)"
.br
.ti -1c
.RI "bool \fBisCreated\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDynamicLibrary\fP \fBgetRunningProcess\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file DynamicLibrary\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::DynamicLibrary::~DynamicLibrary ()"

.SS "mc::DynamicLibrary::DynamicLibrary ()"

.SS "mc::DynamicLibrary::DynamicLibrary (const std::string & path)"

.SS "mc::DynamicLibrary::DynamicLibrary (const char * path)"

.SH "Member Function Documentation"
.PP 
.SS "void mc::DynamicLibrary::destroy ()"

.SS "void* mc::DynamicLibrary::getFunction (const std::string & name)"

.SS "void* mc::DynamicLibrary::getFunction (const char * name)"

.SS "static \fBDynamicLibrary\fP mc::DynamicLibrary::getRunningProcess ()\fC [static]\fP"

.SS "void mc::DynamicLibrary::init (const std::string & path)"

.SS "void mc::DynamicLibrary::init (const char * path)"

.SS "bool mc::DynamicLibrary::isCreated () const"

.SS "void* mc::DynamicLibrary::operator[] (const char * name)\fC [inline]\fP"

.PP
Definition at line 36 of file DynamicLibrary\&.h\&.
.SS "void* mc::DynamicLibrary::operator[] (const std::string & name)\fC [inline]\fP"

.PP
Definition at line 40 of file DynamicLibrary\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
