.TH "mc::Exception" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::Exception \- Superclass that all exceptions in MACE extend\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Constants\&.h>\fP
.PP
Inherits std::runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBException\fP ()=default"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBhandleException\fP (const std::exception &e)"
.br
.RI "\fIStops MACE and prints an exception to console accordingly\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Superclass that all exceptions in MACE extend\&. 
.PP
Definition at line 105 of file Constants\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::Exception::Exception ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static void mc::Exception::handleException (const std::exception & e)\fC [static]\fP"

.PP
Stops MACE and prints an exception to console accordingly\&. This should be used every time a fatal exception is thrown\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
