.TH "mc::gfx::Entity::Metrics" 3 "Sun Apr 9 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::Entity::Metrics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Entity\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector\fP< float, 3 > \fBtranslation\fP"
.br
.ti -1c
.RI "\fBVector\fP< float, 3 > \fBscale\fP"
.br
.ti -1c
.RI "\fBVector\fP< float, 3 > \fBrotation\fP"
.br
.ti -1c
.RI "\fBVector\fP< float, 3 > \fBinheritedTranslation\fP = { 0,0,0 }"
.br
.ti -1c
.RI "\fBVector\fP< float, 3 > \fBinheritedScale\fP = { 1,1,1 }"
.br
.ti -1c
.RI "\fBVector\fP< float, 3 > \fBinheritedRotation\fP = { 0,0,0 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 295 of file Entity\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVector\fP<float, 3> mc::gfx::Entity::Metrics::inheritedRotation = { 0,0,0 }"

.PP
Definition at line 301 of file Entity\&.h\&.
.SS "\fBVector\fP<float, 3> mc::gfx::Entity::Metrics::inheritedScale = { 1,1,1 }"

.PP
Definition at line 300 of file Entity\&.h\&.
.SS "\fBVector\fP<float, 3> mc::gfx::Entity::Metrics::inheritedTranslation = { 0,0,0 }"

.PP
Definition at line 299 of file Entity\&.h\&.
.SS "\fBVector\fP<float, 3> mc::gfx::Entity::Metrics::rotation"

.PP
Definition at line 298 of file Entity\&.h\&.
.SS "\fBVector\fP<float, 3> mc::gfx::Entity::Metrics::scale"

.PP
Definition at line 297 of file Entity\&.h\&.
.SS "\fBVector\fP<float, 3> mc::gfx::Entity::Metrics::translation"

.PP
Definition at line 296 of file Entity\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
