.TH "mc::gfx::Component" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::Component \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Entity\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP (\fBEntity\fP *e)=0"
.br
.ti -1c
.RI "virtual bool \fBupdate\fP (\fBEntity\fP *e)=0"
.br
.ti -1c
.RI "virtual void \fBdestroy\fP (\fBEntity\fP *e)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file Entity\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void mc::gfx::Component::destroy (\fBEntity\fP * e)\fC [pure virtual]\fP"

.SS "virtual void mc::gfx::Component::init (\fBEntity\fP * e)\fC [pure virtual]\fP"

.SS "virtual bool mc::gfx::Component::update (\fBEntity\fP * e)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
