.TH "mc::gfx::Selectable" 3 "Sat Apr 8 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::Selectable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Entity\&.h>\fP
.PP
Inherited by \fBmc::gfx::Button\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisClicked\fP () const "
.br
.ti -1c
.RI "bool \fBisDisabled\fP () const "
.br
.ti -1c
.RI "bool \fBisHovered\fP () const "
.br
.ti -1c
.RI "void \fBclick\fP ()"
.br
.ti -1c
.RI "void \fBdisable\fP ()"
.br
.ti -1c
.RI "void \fBenable\fP ()"
.br
.ti -1c
.RI "void \fBtrigger\fP ()"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "enum \fBSelectableProperty\fP : Byte { \fBCLICKED\fP = 0, \fBDISABLED\fP = 1, \fBHOVERED\fP = 2 }"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBonClick\fP ()"
.br
.ti -1c
.RI "virtual void \fBonEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBonDisable\fP ()"
.br
.ti -1c
.RI "virtual void \fBonTrigger\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBBitField\fP \fBselectableProperties\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 819 of file Entity\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBmc::gfx::Selectable::SelectableProperty\fP : \fBByte\fP\fC [protected]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICLICKED \fP\fP
.TP
\fB\fIDISABLED \fP\fP
.TP
\fB\fIHOVERED \fP\fP
.PP
Definition at line 832 of file Entity\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void mc::gfx::Selectable::click ()"

.SS "void mc::gfx::Selectable::disable ()"

.SS "void mc::gfx::Selectable::enable ()"

.SS "bool mc::gfx::Selectable::isClicked () const"

.SS "bool mc::gfx::Selectable::isDisabled () const"

.SS "bool mc::gfx::Selectable::isHovered () const"

.SS "virtual void mc::gfx::Selectable::onClick ()\fC [protected]\fP, \fC [virtual]\fP"

.SS "virtual void mc::gfx::Selectable::onDisable ()\fC [protected]\fP, \fC [virtual]\fP"

.SS "virtual void mc::gfx::Selectable::onEnable ()\fC [protected]\fP, \fC [virtual]\fP"

.SS "virtual void mc::gfx::Selectable::onTrigger ()\fC [protected]\fP, \fC [virtual]\fP"

.SS "void mc::gfx::Selectable::trigger ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBBitField\fP mc::gfx::Selectable::selectableProperties = 0\fC [protected]\fP"

.PP
Definition at line 838 of file Entity\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
