.TH "mc::gfx::ssl" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::ssl \- Holds resources for the Standard Shader Library (SSL\&.) SSL makes it easy to interact with MACE entities from shaders through special header files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (const \fBSize\fP &originalWidth, const \fBSize\fP &originalHeight)"
.br
.ti -1c
.RI "void \fBsetUp\fP (\fBos::Window\fP *win)"
.br
.ti -1c
.RI "void \fBtearDown\fP (\fBos::Window\fP *win)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void \fBresize\fP (const \fBSize\fP &width, const \fBSize\fP &height)"
.br
.ti -1c
.RI "void \fBbindEntity\fP (const \fBGraphicsEntity\fP *en)"
.br
.ti -1c
.RI "void \fBbindShaderProgram\fP (\fBShaderProgram\fP &prog)"
.br
.ti -1c
.RI "std::string \fBprocessShader\fP (const std::string &shader, const GLenum &type)"
.br
.ti -1c
.RI "const \fBmc::Preprocessor\fP & \fBgetSSLPreprocessor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds resources for the Standard Shader Library (SSL\&.) SSL makes it easy to interact with MACE entities from shaders through special header files\&. 
.SH "Function Documentation"
.PP 
.SS "void mc::gfx::ssl::bindEntity (const \fBGraphicsEntity\fP * en)"

.SS "void mc::gfx::ssl::bindShaderProgram (\fBShaderProgram\fP & prog)"

.SS "void mc::gfx::ssl::destroy ()"

.SS "const \fBmc::Preprocessor\fP& mc::gfx::ssl::getSSLPreprocessor ()"

.SS "void mc::gfx::ssl::init (const \fBSize\fP & originalWidth, const \fBSize\fP & originalHeight)"

.SS "std::string mc::gfx::ssl::processShader (const std::string & shader, const GLenum & type)"

.SS "void mc::gfx::ssl::resize (const \fBSize\fP & width, const \fBSize\fP & height)"

.SS "void mc::gfx::ssl::setUp (\fBos::Window\fP * win)"

.SS "void mc::gfx::ssl::tearDown (\fBos::Window\fP * win)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
