.TH "mc::gfx::Renderer" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::Renderer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBresize\fP (const \fBSize\fP width, const \fBSize\fP hieght)"
.br
.ti -1c
.RI "static void \fBinit\fP (const \fBSize\fP originalWidth, const \fBSize\fP originalHeight)"
.br
.ti -1c
.RI "static void \fBsetUp\fP (\fBos::Window\fP *win)"
.br
.ti -1c
.RI "template<typename T > static void \fBqueue\fP (T *e)"
.br
.ti -1c
.RI "static \fBSize\fP \fBnumberOfProtocols\fP ()"
.br
.ti -1c
.RI "static void \fBtearDown\fP (\fBos::Window\fP *win)"
.br
.ti -1c
.RI "static void \fBrenderFrame\fP (\fBos::Window\fP *win)"
.br
.ti -1c
.RI "static void \fBdestroy\fP ()"
.br
.ti -1c
.RI "static void \fBsetRefreshColor\fP (const float r, const float g, const float b, const float a=1\&.0f)"
.br
.ti -1c
.RI "static void \fBsetRefreshColor\fP (const \fBColor\fP &c)"
.br
.ti -1c
.RI "static \fBSize\fP \fBgetOriginalWidth\fP ()"
.br
.ti -1c
.RI "static \fBSize\fP \fBgetOriginalHeight\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file Renderer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static void mc::gfx::Renderer::destroy ()\fC [static]\fP"

.SS "static \fBSize\fP mc::gfx::Renderer::getOriginalHeight ()\fC [static]\fP"

.SS "static \fBSize\fP mc::gfx::Renderer::getOriginalWidth ()\fC [static]\fP"

.SS "static void mc::gfx::Renderer::init (const \fBSize\fP originalWidth, const \fBSize\fP originalHeight)\fC [static]\fP"

.SS "static \fBSize\fP mc::gfx::Renderer::numberOfProtocols ()\fC [static]\fP"

.SS "template<typename T > static void mc::gfx::Renderer::queue (T * e)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 95 of file Renderer\&.h\&.
.SS "static void mc::gfx::Renderer::renderFrame (\fBos::Window\fP * win)\fC [static]\fP"

.SS "static void mc::gfx::Renderer::resize (const \fBSize\fP width, const \fBSize\fP hieght)\fC [static]\fP"

.SS "static void mc::gfx::Renderer::setRefreshColor (const float r, const float g, const float b, const float a = \fC1\&.0f\fP)\fC [static]\fP"

.SS "static void mc::gfx::Renderer::setRefreshColor (const \fBColor\fP & c)\fC [static]\fP"

.SS "static void mc::gfx::Renderer::setUp (\fBos::Window\fP * win)\fC [static]\fP"

.SS "static void mc::gfx::Renderer::tearDown (\fBos::Window\fP * win)\fC [static]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
