.TH "mc::gfx::AlignmentComponent" 3 "Sun Apr 9 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::AlignmentComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Components\&.h>\fP
.PP
Inherits \fBmc::gfx::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlignmentComponent\fP (const \fBVerticalAlign\fP vert=\fBVerticalAlign::CENTER\fP, const \fBHorizontalAlign\fP horz=\fBHorizontalAlign::CENTER\fP)"
.br
.ti -1c
.RI "void \fBsetVerticalAlign\fP (const \fBVerticalAlign\fP align)"
.br
.ti -1c
.RI "const \fBVerticalAlign\fP \fBgetVerticalAlign\fP () const "
.br
.ti -1c
.RI "void \fBsetHorizontalAlign\fP (\fBHorizontalAlign\fP align)"
.br
.ti -1c
.RI "const \fBHorizontalAlign\fP \fBgetHorizontalAlign\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAlignmentComponent\fP &other) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBAlignmentComponent\fP &other) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBclean\fP (\fBEntity\fP *e) final"
.br
.RI "\fICalled when \fBEntity::clean()\fP is called and it was dirty\&. \fP"
.ti -1c
.RI "virtual void \fBinit\fP (\fBEntity\fP *e)"
.br
.RI "\fICalled when this \fC\fBComponent\fP\fP is added to the \fC\fBEntity\fP\fP via \fBEntity::addComponent(Component&)\fP\&. \fP"
.ti -1c
.RI "virtual bool \fBupdate\fP (\fBEntity\fP *e)"
.br
.RI "\fICalled when \fBEntity::update()\fP is called\&. \fP"
.ti -1c
.RI "virtual void \fBdestroy\fP (\fBEntity\fP *e)"
.br
.RI "\fICalled when \fBEntity::destroy()\fP is called or the \fC\fBComponent\fP\fP is removed via \fBComponent::update(Entity*)\fP, whichever comes first\&. \fP"
.ti -1c
.RI "virtual void \fBrender\fP (\fBEntity\fP *e)"
.br
.ti -1c
.RI "virtual void \fBhover\fP (\fBEntity\fP *e)"
.br
.ti -1c
.RI "\fBEntity\fP * \fBgetParent\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBComponent\fP &other) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBComponent\fP &other) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file Components\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::gfx::AlignmentComponent::AlignmentComponent (const \fBVerticalAlign\fP vert = \fC\fBVerticalAlign::CENTER\fP\fP, const \fBHorizontalAlign\fP horz = \fC\fBHorizontalAlign::CENTER\fP\fP)"

.SH "Member Function Documentation"
.PP 
.SS "void mc::gfx::AlignmentComponent::clean (\fBEntity\fP * e)\fC [final]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Called when \fBEntity::clean()\fP is called and it was dirty\&. This is not required for inheritance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP The parent \fC\fBEntity\fP\fP 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented from \fBmc::gfx::Component\fP\&.
.SS "virtual void mc::gfx::Component::destroy (\fBEntity\fP * e)\fC [protected]\fP, \fC [virtual]\fP, \fC [inherited]\fP"

.PP
Called when \fBEntity::destroy()\fP is called or the \fC\fBComponent\fP\fP is removed via \fBComponent::update(Entity*)\fP, whichever comes first\&. Once \fBComponent::destroy(Entity*)\fP is called, it is immediately removed from the \fC\fBEntity\fP\fP\&. Required function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP The parent \fC\fBEntity\fP\fP 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::FPSComponent\fP, and \fBmc::gfx::CallbackComponent\fP\&.
.SS "const \fBHorizontalAlign\fP mc::gfx::AlignmentComponent::getHorizontalAlign () const"

.SS "\fBEntity\fP* mc::gfx::Component::getParent ()\fC [protected]\fP, \fC [inherited]\fP"

.SS "const \fBVerticalAlign\fP mc::gfx::AlignmentComponent::getVerticalAlign () const"

.SS "virtual void mc::gfx::Component::hover (\fBEntity\fP * e)\fC [protected]\fP, \fC [virtual]\fP, \fC [inherited]\fP"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::FPSComponent\fP, and \fBmc::gfx::CallbackComponent\fP\&.
.SS "virtual void mc::gfx::Component::init (\fBEntity\fP * e)\fC [protected]\fP, \fC [virtual]\fP, \fC [inherited]\fP"

.PP
Called when this \fC\fBComponent\fP\fP is added to the \fC\fBEntity\fP\fP via \fBEntity::addComponent(Component&)\fP\&. Required function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP The parent \fC\fBEntity\fP\fP 
.RE
.PP
\fBNote:\fP
.RS 4
This is not called at \fBEntity::init()\fP, instead it is called when the component is added to the \fC\fBEntity\fP\fP\&. Keep that in mind\&. 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::FPSComponent\fP, and \fBmc::gfx::CallbackComponent\fP\&.
.SS "bool mc::gfx::AlignmentComponent::operator!= (const \fBAlignmentComponent\fP & other) const"

.SS "bool mc::gfx::Component::operator!= (const \fBComponent\fP & other) const\fC [protected]\fP, \fC [inherited]\fP"

.SS "bool mc::gfx::AlignmentComponent::operator== (const \fBAlignmentComponent\fP & other) const"

.SS "bool mc::gfx::Component::operator== (const \fBComponent\fP & other) const\fC [protected]\fP, \fC [inherited]\fP"

.SS "virtual void mc::gfx::Component::render (\fBEntity\fP * e)\fC [protected]\fP, \fC [virtual]\fP, \fC [inherited]\fP"

.PP
Reimplemented in \fBmc::gfx::FPSComponent\fP, and \fBmc::gfx::CallbackComponent\fP\&.
.SS "void mc::gfx::AlignmentComponent::setHorizontalAlign (\fBHorizontalAlign\fP align)"

.PP
\fBNote:\fP
.RS 4
This will make this \fC\fBEntity\fP\fP dirty\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBEntity::DIRTY\fP 
.RE
.PP

.SS "void mc::gfx::AlignmentComponent::setVerticalAlign (const \fBVerticalAlign\fP align)"

.PP
\fBNote:\fP
.RS 4
This will make this \fC\fBEntity\fP\fP dirty\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBEntity::DIRTY\fP 
.RE
.PP

.SS "virtual bool mc::gfx::Component::update (\fBEntity\fP * e)\fC [protected]\fP, \fC [virtual]\fP, \fC [inherited]\fP"

.PP
Called when \fBEntity::update()\fP is called\&. Required function\&. 
.PP
There is no function to remove a \fC\fBComponent\fP\fP so this is the only way for a \fC\fBComponent\fP\fP to be removed from an \fC\fBEntity\fP\fP 
.PP
\fBComponent::destroy(Entity*)\fP will be called afterwards\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP The parent \fC\fBEntity\fP\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Whether this \fC\fBComponent\fP\fP should be deleted or not\&. 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::FPSComponent\fP, and \fBmc::gfx::CallbackComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
