.TH "mc::gfx::Font" 3 "Sat Jan 14 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::Font \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Entity2D\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFont\fP (const \fBFont\fP &f)"
.br
.ti -1c
.RI "\fBFont\fP (const \fBIndex\fP id=0, const \fBSize\fP h=0)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void \fBgetCharacter\fP (const wchar_t character, \fBLetter\fP *let) const "
.br
.ti -1c
.RI "void \fBsetSize\fP (const \fBSize\fP height)"
.br
.ti -1c
.RI "\fBSize\fP & \fBgetSize\fP ()"
.br
.ti -1c
.RI "const \fBSize\fP & \fBgetSize\fP () const "
.br
.ti -1c
.RI "\fBIndex\fP \fBgetID\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFont\fP &other) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBFont\fP &other) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFont\fP \fBloadFont\fP (const std::string &name)"
.br
.ti -1c
.RI "static \fBFont\fP \fBloadFont\fP (const char *name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 239 of file Entity2D\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::gfx::Font::Font (const \fBFont\fP & f)"

.SS "mc::gfx::Font::Font (const \fBIndex\fP id = \fC0\fP, const \fBSize\fP h = \fC0\fP)"

.SH "Member Function Documentation"
.PP 
.SS "void mc::gfx::Font::destroy ()"

.SS "void mc::gfx::Font::getCharacter (const wchar_t character, \fBLetter\fP * let) const"

.PP
\fBTodo\fP
.RS 4
find a way to dynamically allocate letters without passing in a pointer 
.RE
.PP

.SS "\fBIndex\fP mc::gfx::Font::getID () const"

.SS "\fBSize\fP& mc::gfx::Font::getSize ()"

.SS "const \fBSize\fP& mc::gfx::Font::getSize () const"

.SS "static \fBFont\fP mc::gfx::Font::loadFont (const std::string & name)\fC [static]\fP"

.SS "static \fBFont\fP mc::gfx::Font::loadFont (const char * name)\fC [static]\fP"

.SS "bool mc::gfx::Font::operator!= (const \fBFont\fP & other) const"

.SS "bool mc::gfx::Font::operator== (const \fBFont\fP & other) const"

.SS "void mc::gfx::Font::setSize (const \fBSize\fP height)"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
