.TH "mc::gfx::Renderer" 3 "Wed Feb 1 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::Renderer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBresize\fP (const \fBSize\fP width, const \fBSize\fP hieght)"
.br
.ti -1c
.RI "static void \fBinit\fP (const \fBSize\fP originalWidth, const \fBSize\fP originalHeight)"
.br
.ti -1c
.RI "static void \fBinitEntity\fP (\fBGraphicsEntity\fP *en, const \fBIndex\fP protocol)"
.br
.ti -1c
.RI "static void \fBsetUp\fP (\fBos::WindowModule\fP *win)"
.br
.ti -1c
.RI "static void \fBqueue\fP (\fBGraphicsEntity\fP *e, const \fBIndex\fP protocol)"
.br
.ti -1c
.RI "static \fBSize\fP \fBnumberOfProtocols\fP ()"
.br
.ti -1c
.RI "static void \fBtearDown\fP (\fBos::WindowModule\fP *win)"
.br
.ti -1c
.RI "static void \fBrenderFrame\fP (\fBos::WindowModule\fP *win)"
.br
.ti -1c
.RI "static void \fBcheckInput\fP ()"
.br
.ti -1c
.RI "static void \fBcleanEntity\fP (\fBGraphicsEntity\fP *en, const \fBIndex\fP protocol)"
.br
.ti -1c
.RI "static void \fBdestroy\fP ()"
.br
.ti -1c
.RI "static void \fBdestroyEntity\fP (\fBGraphicsEntity\fP *en, const \fBIndex\fP protocol)"
.br
.ti -1c
.RI "static void \fBclearBuffers\fP ()"
.br
.ti -1c
.RI "static void \fBsetRefreshColor\fP (const float r, const float g, const float b, const float a=1\&.0f)"
.br
.ti -1c
.RI "static void \fBsetRefreshColor\fP (const \fBColor\fP &c)"
.br
.ti -1c
.RI "template<typename T > static \fBIndex\fP \fBregisterProtocol\fP ()"
.br
.ti -1c
.RI "static \fBSize\fP \fBgetOriginalWidth\fP ()"
.br
.ti -1c
.RI "static \fBSize\fP \fBgetOriginalHeight\fP ()"
.br
.ti -1c
.RI "static \fBSize\fP \fBgetSamples\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBTodo\fP
.RS 4
add function to change how many samples msaa uses 
.RE
.PP

.PP
Definition at line 193 of file Renderer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static void mc::gfx::Renderer::checkInput ()\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::cleanEntity (\fBGraphicsEntity\fP * en, const \fBIndex\fP protocol)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::clearBuffers ()\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::destroy ()\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::destroyEntity (\fBGraphicsEntity\fP * en, const \fBIndex\fP protocol)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static \fBSize\fP mc::gfx::Renderer::getOriginalHeight ()\fC [static]\fP"

.SS "static \fBSize\fP mc::gfx::Renderer::getOriginalWidth ()\fC [static]\fP"

.SS "static \fBSize\fP mc::gfx::Renderer::getSamples ()\fC [static]\fP"

.SS "static void mc::gfx::Renderer::init (const \fBSize\fP originalWidth, const \fBSize\fP originalHeight)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::initEntity (\fBGraphicsEntity\fP * en, const \fBIndex\fP protocol)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static \fBSize\fP mc::gfx::Renderer::numberOfProtocols ()\fC [static]\fP"

.SS "static void mc::gfx::Renderer::queue (\fBGraphicsEntity\fP * e, const \fBIndex\fP protocol)\fC [static]\fP"

.SS "template<typename T > static \fBIndex\fP mc::gfx::Renderer::registerProtocol ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 276 of file Renderer\&.h\&.
.SS "static void mc::gfx::Renderer::renderFrame (\fBos::WindowModule\fP * win)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::resize (const \fBSize\fP width, const \fBSize\fP hieght)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::setRefreshColor (const float r, const float g, const float b, const float a = \fC1\&.0f\fP)\fC [static]\fP"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::setRefreshColor (const \fBColor\fP & c)\fC [static]\fP"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::setUp (\fBos::WindowModule\fP * win)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "static void mc::gfx::Renderer::tearDown (\fBos::WindowModule\fP * win)\fC [static]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
