.TH "mc::gfx::ogl" 3 "Sat Apr 8 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::ogl \- Contains various abstractions for OpenGL\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBuffer\fP"
.br
.RI "\fIRepresents a sslBuffer of memory in the GPU\&. \fP"
.ti -1c
.RI "class \fBCopyReadBuffer\fP"
.br
.RI "\fISpecial sslBuffer with no extra semantics to be used as a proxy in copying\&. \fP"
.ti -1c
.RI "class \fBCopyWriteBuffer\fP"
.br
.RI "\fISpecial sslBuffer with no extra semantics to be used as a proxy in copying\&. \fP"
.ti -1c
.RI "class \fBElementBuffer\fP"
.br
.RI "\fIStores element indices to save vertex data\&. \fP"
.ti -1c
.RI "class \fBFrameBuffer\fP"
.br
.RI "\fIRepresents an OpenGL Framebuffer \fBObject\fP which allows rendering to a non-screen location\&. \fP"
.ti -1c
.RI "class \fBObject\fP"
.br
.RI "\fIRepresents a OpenGL object in memory\&. \fP"
.ti -1c
.RI "class \fBPixelPackBuffer\fP"
.br
.RI "\fISpecial sslBuffer that excels at asynchronous pixel transfer operations\&. \fP"
.ti -1c
.RI "class \fBPixelUnpackBuffer\fP"
.br
.RI "\fISpecial sslBuffer that excels at asynchronous pixel transfer operations\&. \fP"
.ti -1c
.RI "class \fBQueryObject\fP"
.br
.RI "\fISpecial object that is used for asynchronous queries of information from the GPU\&. \fP"
.ti -1c
.RI "class \fBRenderBuffer\fP"
.br
.RI "\fIRepresents a render buffer for use with a `FrameBuffer\&. \fP"
.ti -1c
.RI "class \fBShader\fP"
.br
.RI "\fIRepresents a shader object in OpenGL\&. \fP"
.ti -1c
.RI "class \fBShaderProgram\fP"
.br
.ti -1c
.RI "class \fBTexture2D\fP"
.br
.ti -1c
.RI "class \fBUniformBuffer\fP"
.br
.RI "\fIStores uniform data for a shader in the form of a sslBuffer\&. \fP"
.ti -1c
.RI "class \fBVertexArray\fP"
.br
.ti -1c
.RI "class \fBVertexBuffer\fP"
.br
.RI "\fIStores vertex data for a `VertexArray\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_MACE_DECLARE_ERROR\fP (OpenGL)"
.br
.RI "\fIThrown when OpenGL fails or errors\&. \fP"
.ti -1c
.RI "\fB_MACE_DECLARE_ERROR\fP (\fBShader\fP)"
.br
.RI "\fIThrown when a \fBShader\fP throws an exception, such as a failed compilation\&. \fP"
.ti -1c
.RI "\fB_MACE_DECLARE_ERROR\fP (Framebuffer)"
.br
.RI "\fIThrown when a Framebuffer fails to be created, or throws an error\&. \fP"
.ti -1c
.RI "void \fBcheckGLError\fP (const \fBIndex\fP line=0, const char *file='Unknown file', const char *message='No message specified')"
.br
.ti -1c
.RI "void \fBcheckGLError\fP (const \fBIndex\fP line, const std::string &file, const std::string message)"
.br
.ti -1c
.RI "void \fBenable\fP (const \fBEnum\fP param)"
.br
.ti -1c
.RI "void \fBdisable\fP (const \fBEnum\fP param)"
.br
.ti -1c
.RI "void \fBsetBlending\fP (const \fBEnum\fP sfactor, const \fBEnum\fP dfactor)"
.br
.ti -1c
.RI "void \fBsetViewport\fP (const \fBIndex\fP x, const \fBIndex\fP y, const \fBSize\fP width, const \fBSize\fP height)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains various abstractions for OpenGL\&. 

Assume that any class in this namespace requires an OpenGL context\&. 
.PP
OpenGL abstractions will only implement functionality from OpenGL 3\&.3, as that is what \fBMACE\fP supports\&. 
.PP
Most of the abstractions have very minimal extra work\&. Most of the time they are direct bindings to the actual OpenGL function\&. However, some classes like \fC\fBShaderProgram\fP\fP do a lot of bookkeeping to make it easier to use\&. 
.PP
The documentation for classes in the \fCogl\fP namespace assumes that you understand the underlying OpenGL concepts\&. A link to a page about the OpenGL concept is usually present\&. 
.PP
Each abstraction follows a very similar syntax and style to make it easier to understand\&. 
.PP
\fBSee also:\fP
.RS 4
\fBObject\fP 
.PP
\fBBuffer\fP 
.RE
.PP
\fBTodo\fP
.RS 4
create a ReadableBuffer class with functions like glReadPixels 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "mc::gfx::ogl::_MACE_DECLARE_ERROR (OpenGL)"

.PP
Thrown when OpenGL fails or errors\&. 
.PP
\fBSee also:\fP
.RS 4
ShaderError 
.RE
.PP

.SS "mc::gfx::ogl::_MACE_DECLARE_ERROR (\fBShader\fP)"

.PP
Thrown when a \fBShader\fP throws an exception, such as a failed compilation\&. 
.PP
\fBSee also:\fP
.RS 4
OpenGLError 
.RE
.PP

.SS "mc::gfx::ogl::_MACE_DECLARE_ERROR (Framebuffer)"

.PP
Thrown when a Framebuffer fails to be created, or throws an error\&. 
.PP
\fBSee also:\fP
.RS 4
gfx::ogl::Framebuffer 
.PP
OpenGLError 
.RE
.PP

.SS "void mc::gfx::ogl::checkGLError (const \fBIndex\fP line = \fC0\fP, const char * file = \fC'Unknown file'\fP, const char * message = \fC'No message specified'\fP)"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ogl::checkGLError (const \fBIndex\fP line, const std::string & file, const std::string message)"

.PP

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ogl::disable (const \fBEnum\fP param)"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ogl::enable (const \fBEnum\fP param)"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ogl::setBlending (const \fBEnum\fP sfactor, const \fBEnum\fP dfactor)"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ogl::setViewport (const \fBIndex\fP x, const \fBIndex\fP y, const \fBSize\fP width, const \fBSize\fP height)"

.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
