.TH "mc::gfx::RenderProtocol< T >" 3 "Sat Apr 8 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::RenderProtocol< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer\&.h>\fP
.PP
Inherits \fBmc::gfx::RenderImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBresize\fP (const \fBSize\fP, const \fBSize\fP) override"
.br
.ti -1c
.RI "void \fBinit\fP (const \fBSize\fP, const \fBSize\fP) override"
.br
.ti -1c
.RI "void \fBinitEntity\fP (\fBGraphicsEntity\fP *) override"
.br
.ti -1c
.RI "void \fBsetUp\fP (\fBos::WindowModule\fP *, \fBRenderQueue\fP *) override"
.br
.ti -1c
.RI "void \fBrenderEntity\fP (\fBos::WindowModule\fP *, \fBGraphicsEntity\fP *) override"
.br
.ti -1c
.RI "void \fBtearDown\fP (\fBos::WindowModule\fP *, \fBRenderQueue\fP *) override"
.br
.ti -1c
.RI "void \fBcleanEntity\fP (\fBGraphicsEntity\fP *) override"
.br
.ti -1c
.RI "void \fBdestroy\fP () override"
.br
.ti -1c
.RI "void \fBdestroyEntity\fP (\fBGraphicsEntity\fP *) override"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class mc::gfx::RenderProtocol< T >"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Definition at line 170 of file Renderer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::cleanEntity (\fBGraphicsEntity\fP *)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented from \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 183 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::destroy ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Implements \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 185 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::destroyEntity (\fBGraphicsEntity\fP *)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented from \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 186 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::init (const \fBSize\fP, const \fBSize\fP)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Implements \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 176 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::initEntity (\fBGraphicsEntity\fP *)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented from \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 177 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::renderEntity (\fBos::WindowModule\fP *, \fBGraphicsEntity\fP * entity)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Implements \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 180 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::resize (const \fBSize\fP, const \fBSize\fP)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented from \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 174 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::setUp (\fBos::WindowModule\fP *, \fBRenderQueue\fP *)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented from \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 179 of file Renderer\&.h\&.
.SS "template<typename T > void \fBmc::gfx::RenderProtocol\fP< T >::tearDown (\fBos::WindowModule\fP *, \fBRenderQueue\fP *)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented from \fBmc::gfx::RenderImpl\fP\&.
.PP
Definition at line 181 of file Renderer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
