.TH "mc::gfx::RenderImpl" 3 "Wed Feb 1 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::RenderImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer\&.h>\fP
.PP
Inherited by \fBmc::gfx::RenderProtocol< T >\fP, \fBmc::gfx::RenderProtocol< Image >\fP, \fBmc::gfx::RenderProtocol< Letter >\fP, and \fBmc::gfx::RenderProtocol< ProgressBar >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderImpl\fP () noexcept=default"
.br
.ti -1c
.RI "virtual \fB~RenderImpl\fP () noexcept=default"
.br
.ti -1c
.RI "virtual void \fBresize\fP (const \fBSize\fP, const \fBSize\fP)"
.br
.ti -1c
.RI "virtual void \fBinit\fP (const \fBSize\fP, const \fBSize\fP)=0"
.br
.ti -1c
.RI "virtual void \fBinitEntity\fP (\fBGraphicsEntity\fP *)"
.br
.ti -1c
.RI "virtual void \fBsetUp\fP (\fBos::WindowModule\fP *, \fBRenderQueue\fP *)"
.br
.ti -1c
.RI "virtual void \fBrenderEntity\fP (\fBos::WindowModule\fP *, \fBGraphicsEntity\fP *entity)=0"
.br
.ti -1c
.RI "virtual void \fBtearDown\fP (\fBos::WindowModule\fP *, \fBRenderQueue\fP *)"
.br
.ti -1c
.RI "virtual void \fBcleanEntity\fP (\fBGraphicsEntity\fP *)"
.br
.ti -1c
.RI "virtual void \fBdestroy\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdestroyEntity\fP (\fBGraphicsEntity\fP *)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRenderer\fP"
.br
.ti -1c
.RI "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP

.PP
Definition at line 105 of file Renderer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::gfx::RenderImpl::RenderImpl ()\fC [default]\fP, \fC [noexcept]\fP"

.SS "virtual mc::gfx::RenderImpl::~RenderImpl ()\fC [virtual]\fP, \fC [default]\fP, \fC [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void mc::gfx::RenderImpl::cleanEntity (\fBGraphicsEntity\fP *)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::RenderProtocol< T >\fP\&.
.PP
Definition at line 150 of file Renderer\&.h\&.
.SS "virtual void mc::gfx::RenderImpl::destroy ()\fC [pure virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Implemented in \fBmc::gfx::RenderProtocol< Letter >\fP, \fBmc::gfx::RenderProtocol< T >\fP, \fBmc::gfx::RenderProtocol< ProgressBar >\fP, and \fBmc::gfx::RenderProtocol< Image >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::destroyEntity (\fBGraphicsEntity\fP *)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::RenderProtocol< T >\fP\&.
.PP
Definition at line 161 of file Renderer\&.h\&.
.SS "virtual void mc::gfx::RenderImpl::init (const \fBSize\fP, const \fBSize\fP)\fC [pure virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Implemented in \fBmc::gfx::RenderProtocol< Letter >\fP, \fBmc::gfx::RenderProtocol< T >\fP, \fBmc::gfx::RenderProtocol< ProgressBar >\fP, and \fBmc::gfx::RenderProtocol< Image >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::initEntity (\fBGraphicsEntity\fP *)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::RenderProtocol< Letter >\fP, \fBmc::gfx::RenderProtocol< T >\fP, \fBmc::gfx::RenderProtocol< ProgressBar >\fP, and \fBmc::gfx::RenderProtocol< Image >\fP\&.
.PP
Definition at line 128 of file Renderer\&.h\&.
.SS "virtual void mc::gfx::RenderImpl::renderEntity (\fBos::WindowModule\fP *, \fBGraphicsEntity\fP * entity)\fC [pure virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Implemented in \fBmc::gfx::RenderProtocol< Letter >\fP, \fBmc::gfx::RenderProtocol< T >\fP, \fBmc::gfx::RenderProtocol< ProgressBar >\fP, and \fBmc::gfx::RenderProtocol< Image >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::resize (const \fBSize\fP, const \fBSize\fP)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::RenderProtocol< T >\fP\&.
.PP
Definition at line 117 of file Renderer\&.h\&.
.SS "virtual void mc::gfx::RenderImpl::setUp (\fBos::WindowModule\fP *, \fBRenderQueue\fP *)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::RenderProtocol< T >\fP\&.
.PP
Definition at line 134 of file Renderer\&.h\&.
.SS "virtual void mc::gfx::RenderImpl::tearDown (\fBos::WindowModule\fP *, \fBRenderQueue\fP *)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.PP
Reimplemented in \fBmc::gfx::RenderProtocol< T >\fP\&.
.PP
Definition at line 144 of file Renderer\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBRenderer\fP\fC [friend]\fP"

.PP
Definition at line 106 of file Renderer\&.h\&.
.SS "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
