.TH "mc::gfx::RenderImpl" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::RenderImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Renderer\&.h>\fP
.PP
Inherited by \fBmc::gfx::RenderProtocol< T >\fP, and \fBmc::gfx::RenderProtocol< Entity2D >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderImpl\fP ()"
.br
.ti -1c
.RI "virtual \fB~RenderImpl\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBresize\fP (const \fBSize\fP width, const \fBSize\fP height)=0"
.br
.ti -1c
.RI "virtual void \fBinit\fP (const \fBSize\fP originalWidth, const \fBSize\fP originalHeight)=0"
.br
.ti -1c
.RI "virtual void \fBsetUp\fP (\fBos::Window\fP *win, \fBRenderQueue\fP *queue)=0"
.br
.ti -1c
.RI "virtual void \fBrender\fP (\fBos::Window\fP *win, \fBEntity\fP *entity)=0"
.br
.ti -1c
.RI "virtual void \fBtearDown\fP (\fBos::Window\fP *win, \fBRenderQueue\fP *queue)=0"
.br
.ti -1c
.RI "virtual void \fBdestroy\fP ()=0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRenderer\fP"
.br
.ti -1c
.RI "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file Renderer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::gfx::RenderImpl::RenderImpl ()"

.SS "virtual mc::gfx::RenderImpl::~RenderImpl ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void mc::gfx::RenderImpl::destroy ()\fC [pure virtual]\fP"

.PP
Implemented in \fBmc::gfx::RenderProtocol< T >\fP, and \fBmc::gfx::RenderProtocol< Entity2D >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::init (const \fBSize\fP originalWidth, const \fBSize\fP originalHeight)\fC [pure virtual]\fP"

.PP
Implemented in \fBmc::gfx::RenderProtocol< T >\fP, and \fBmc::gfx::RenderProtocol< Entity2D >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::render (\fBos::Window\fP * win, \fBEntity\fP * entity)\fC [pure virtual]\fP"

.PP
Implemented in \fBmc::gfx::RenderProtocol< T >\fP, and \fBmc::gfx::RenderProtocol< Entity2D >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::resize (const \fBSize\fP width, const \fBSize\fP height)\fC [pure virtual]\fP"

.PP
Implemented in \fBmc::gfx::RenderProtocol< T >\fP, and \fBmc::gfx::RenderProtocol< Entity2D >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::setUp (\fBos::Window\fP * win, \fBRenderQueue\fP * queue)\fC [pure virtual]\fP"

.PP
Implemented in \fBmc::gfx::RenderProtocol< T >\fP, and \fBmc::gfx::RenderProtocol< Entity2D >\fP\&.
.SS "virtual void mc::gfx::RenderImpl::tearDown (\fBos::Window\fP * win, \fBRenderQueue\fP * queue)\fC [pure virtual]\fP"

.PP
Implemented in \fBmc::gfx::RenderProtocol< T >\fP, and \fBmc::gfx::RenderProtocol< Entity2D >\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBRenderer\fP\fC [friend]\fP"

.PP
Definition at line 51 of file Renderer\&.h\&.
.SS "void \fBssl::init\fP (const \fBSize\fP &, const \fBSize\fP &)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
