.TH "mc::gfx::ssl" 3 "Sun Apr 9 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::ssl \- Holds resources for the Standard Shader Library (SSL\&.) SSL makes it easy to interact with \fBMACE\fP entities from shaders through special header files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfillBuffer\fP (\fBGraphicsEntity\fP *en)"
.br
.ti -1c
.RI "void \fBbindBuffer\fP (\fBogl::UniformBuffer\fP &buf)"
.br
.ti -1c
.RI "void \fBbindEntity\fP (const \fBGraphicsEntity\fP *en, \fBogl::ShaderProgram\fP &prog)"
.br
.ti -1c
.RI "void \fBcheckInput\fP (\fBos::WindowModule\fP *win)"
.br
.ti -1c
.RI "void \fBinit\fP (const \fBSize\fP &originalWidth, const \fBSize\fP &originalHeight)"
.br
.ti -1c
.RI "void \fBsetUp\fP (\fBos::WindowModule\fP *win)"
.br
.ti -1c
.RI "void \fBtearDown\fP (\fBos::WindowModule\fP *win)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void \fBresize\fP (const \fBSize\fP &width, const \fBSize\fP &height)"
.br
.ti -1c
.RI "void \fBbindShaderProgram\fP (\fBogl::ShaderProgram\fP &prog)"
.br
.ti -1c
.RI "std::string \fBprocessShader\fP (const std::string &shader, const GLenum &type)"
.br
.ti -1c
.RI "const \fBmc::Preprocessor\fP & \fBgetSSLPreprocessor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds resources for the Standard Shader Library (SSL\&.) SSL makes it easy to interact with \fBMACE\fP entities from shaders through special header files\&. 


.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void mc::gfx::ssl::bindBuffer (\fBogl::UniformBuffer\fP & buf)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ssl::bindEntity (const \fBGraphicsEntity\fP * en, \fBogl::ShaderProgram\fP & prog)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ssl::bindShaderProgram (\fBogl::ShaderProgram\fP & prog)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ssl::checkInput (\fBos::WindowModule\fP * win)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ssl::destroy ()"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ssl::fillBuffer (\fBGraphicsEntity\fP * en)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "const \fBmc::Preprocessor\fP& mc::gfx::ssl::getSSLPreprocessor ()"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP

.SS "void mc::gfx::ssl::init (const \fBSize\fP & originalWidth, const \fBSize\fP & originalHeight)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "std::string mc::gfx::ssl::processShader (const std::string & shader, const GLenum & type)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP

.SS "void mc::gfx::ssl::resize (const \fBSize\fP & width, const \fBSize\fP & height)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ssl::setUp (\fBos::WindowModule\fP * win)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SS "void mc::gfx::ssl::tearDown (\fBos::WindowModule\fP * win)"

.PP
\fBWarning:\fP
.RS 4
This should only be used internally or by advanced users\&. Misuse can cause undefined behavior 
.RE
.PP
\fBAttention:\fP
.RS 4
This uses an OpenGL function and must be called in a thread with an OpenGL context\&. Otherwise, an error will be thrown\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIGL_INVALID_OPERATION\fP If the current thread does not have an OpenGL context 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
