.TH "mc::gfx::RenderBuffer" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::gfx::RenderBuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Buffer\&.h>\fP
.PP
Inherits \fBmc::gfx::Object\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "void \fBsetStorage\fP (const GLenum &format, const GLsizei &width, const GLsizei &height)"
.br
.ti -1c
.RI "void \fBsetStorageMultisampled\fP (const GLsizei &samples, const GLenum &format, const GLsizei &width, const GLsizei &height)"
.br
.ti -1c
.RI "bool \fBisCreated\fP () const "
.br
.ti -1c
.RI "void \fBbind\fP () const "
.br
.ti -1c
.RI "void \fBunbind\fP () const "
.br
.ti -1c
.RI "\fBIndex\fP \fBgetID\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBIndex\fP \fBid\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 106 of file Buffer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void mc::gfx::Object::bind () const\fC [inherited]\fP"

.SS "void mc::gfx::RenderBuffer::destroy ()\fC [virtual]\fP"

.PP
Implements \fBmc::gfx::Object\fP\&.
.SS "\fBIndex\fP mc::gfx::Object::getID () const\fC [inherited]\fP"

.SS "void mc::gfx::RenderBuffer::init ()\fC [virtual]\fP"

.PP
Implements \fBmc::gfx::Object\fP\&.
.SS "bool mc::gfx::RenderBuffer::isCreated () const\fC [virtual]\fP"

.PP
Implements \fBmc::gfx::Object\fP\&.
.SS "void mc::gfx::RenderBuffer::setStorage (const GLenum & format, const GLsizei & width, const GLsizei & height)"

.SS "void mc::gfx::RenderBuffer::setStorageMultisampled (const GLsizei & samples, const GLenum & format, const GLsizei & width, const GLsizei & height)"

.SS "void mc::gfx::Object::unbind () const\fC [inherited]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBIndex\fP mc::gfx::Object::id = 0\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line 37 of file Buffer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
