.TH "mc::IncludeString" 3 "Sat Apr 8 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::IncludeString \- Represents a fake file, in which you can add include files that don't exist on the filesystem\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Preprocessor\&.h>\fP
.PP
Inherits \fBmc::Include\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIncludeString\fP (const std::string &content, const std::string name)"
.br
.RI "\fICreates an \fC\fBIncludeString\fP\fP with the specified info\&. \fP"
.ti -1c
.RI "bool \fBhasFile\fP (const std::string &name) const "
.br
.RI "\fIChecks whether this include has the specified file\&. \fP"
.ti -1c
.RI "std::string \fBgetFile\fP (const std::string &name) const "
.br
.RI "\fIRetrieves a file with a certain name\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents a fake file, in which you can add include files that don't exist on the filesystem\&. 


.PP
\fBSee also:\fP
.RS 4
\fBIncludeDirectory\fP 
.PP
\fBPreprocessor\fP 
.RE
.PP

.PP
Definition at line 92 of file Preprocessor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::IncludeString::IncludeString (const std::string & content, const std::string name)"

.PP
Creates an \fC\fBIncludeString\fP\fP with the specified info\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcontent\fP What the \fC\fBIncludeString\fP\fP returns when included 
.br
\fIname\fP The name of the \fC\fBIncludeString\fP\fP which is used by #include 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string mc::IncludeString::getFile (const std::string & name) const\fC [virtual]\fP"

.PP
Retrieves a file with a certain name\&. 
.PP
Implements \fBmc::Include\fP\&.
.SS "bool mc::IncludeString::hasFile (const std::string & name) const\fC [virtual]\fP"

.PP
Checks whether this include has the specified file\&. If there isn't an \fC\fBInclude\fP\fP with the file, then a \fCPreprocessorException\fP is thrown\&. 
.PP
Implements \fBmc::Include\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
