.TH "mc::Include" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::Include \- Superclass for classes that represent items that can be included via #include\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Preprocessor\&.h>\fP
.PP
Inherited by \fBmc::IncludeDirectory\fP, and \fBmc::IncludeString\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBhasFile\fP (const std::string &name) const  =0"
.br
.RI "\fIChecks whether this include has the specified file\&. \fP"
.ti -1c
.RI "virtual std::string \fBgetFile\fP (const std::string &name) const  =0"
.br
.RI "\fIRetrieves a file with a certain name\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Superclass for classes that represent items that can be included via #include\&. 


.PP
\fBSee also:\fP
.RS 4
\fBIncludeString\fP 
.PP
\fBIncludeDirectory\fP 
.PP
\fBPreprocessor\fP 
.RE
.PP

.PP
Definition at line 75 of file Preprocessor\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string mc::Include::getFile (const std::string & name) const\fC [pure virtual]\fP"

.PP
Retrieves a file with a certain name\&. 
.PP
Implemented in \fBmc::IncludeDirectory\fP, and \fBmc::IncludeString\fP\&.
.SS "virtual bool mc::Include::hasFile (const std::string & name) const\fC [pure virtual]\fP"

.PP
Checks whether this include has the specified file\&. If there isn't an \fC\fBInclude\fP\fP with the file, then a \fCPreprocessorException\fP is thrown\&. 
.PP
Implemented in \fBmc::IncludeDirectory\fP, and \fBmc::IncludeString\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
