.TH "mc::Module" 3 "Sat Jan 14 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::Module \- Abstract class used for doing a task in \fBMACE\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Module\&.h>\fP
.PP
Inherited by \fBmc::AudioModule\fP, and \fBmc::os::WindowModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP ()=0"
.br
.RI "\fICalled when \fBMACE#init\fP is called and this \fC\fBModule\fP\fP is registered\&. \fP"
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.RI "\fICalled when \fBMACE#update\fP is called and this \fC\fBModule\fP\fP is registered\&. \fP"
.ti -1c
.RI "virtual void \fBdestroy\fP ()=0"
.br
.RI "\fICalled when \fBMACE#destroy\fP is called and this \fC\fBModule\fP\fP is registered\&. \fP"
.ti -1c
.RI "virtual std::string \fBgetName\fP () const  =0"
.br
.RI "\fIOverride this function and return a UNIQUE name for this \fC\fBModule\fP\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
Abstract class used for doing a task in \fBMACE\fP\&. 

Plugged into \fBMACE\fP via \fBaddModule()\&.\fP 
.PP
Definition at line 22 of file Module\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void mc::Module::destroy ()\fC [pure virtual]\fP"

.PP
Called when \fBMACE#destroy\fP is called and this \fC\fBModule\fP\fP is registered\&. Use this to clear memory, close streams, or clean up anything that needs to be cleaned up\&. 
.PP
Should only be called before the program is closed\&. 
.PP
Implemented in \fBmc::os::WindowModule\fP\&.
.SS "virtual std::string mc::Module::getName () const\fC [pure virtual]\fP"

.PP
Override this function and return a UNIQUE name for this \fC\fBModule\fP\fP The name for your \fC\fBModule\fP\fP is used in comparison, so make sure it is as unique as possible\&. 
.PP
It is akin to a hashcode\&. 
.PP
Implemented in \fBmc::os::WindowModule\fP\&.
.SS "virtual void mc::Module::init ()\fC [pure virtual]\fP"

.PP
Called when \fBMACE#init\fP is called and this \fC\fBModule\fP\fP is registered\&. Use this to initialize variables, start streams, or launch a context\&. 
.PP
Should only be called once\&. 
.PP
Implemented in \fBmc::os::WindowModule\fP\&.
.SS "virtual void mc::Module::update ()\fC [pure virtual]\fP"

.PP
Called when \fBMACE#update\fP is called and this \fC\fBModule\fP\fP is registered\&. Use this update states, send messages, swap graphics buffers, render, process, or anything that needs to be periodically checked\&. 
.PP
Implemented in \fBmc::os::WindowModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
