.TH "mc::os::SignalAbortError" 3 "Sun Apr 9 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::os::SignalAbortError \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Signal\&.h>\fP
.PP
Inherits \fBmc::os::SignalError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetErrorDump\fP (const std::exception &e)"
.br
.ti -1c
.RI "static void \fBsetLogFileEnabled\fP (const bool &writeLog)"
.br
.ti -1c
.RI "static void \fBsetVerboseErrors\fP (const bool &verbose)"
.br
.ti -1c
.RI "static void \fBhandleError\fP (const std::exception &e)"
.br
.RI "\fIStops \fBMACE\fP and prints an exception to console accordingly\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file Signal\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static std::string mc::Error::getErrorDump (const std::exception & e)\fC [static]\fP, \fC [inherited]\fP"

.SS "void mc::Error::handle ()\fC [inherited]\fP"

.SS "static void mc::Error::handleError (const std::exception & e)\fC [static]\fP, \fC [inherited]\fP"

.PP
Stops \fBMACE\fP and prints an exception to console accordingly\&. This should be used every time a fatal exception is thrown\&. 
.SS "static void mc::Error::setLogFileEnabled (const bool & writeLog)\fC [static]\fP, \fC [inherited]\fP"

.SS "static void mc::Error::setVerboseErrors (const bool & verbose)\fC [static]\fP, \fC [inherited]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
