.TH "mc::os::Window" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::os::Window \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Window\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (const int width, const int height, const char *\fBtitle\fP)"
.br
.ti -1c
.RI "GLFWwindow * \fBgetGLFWWindow\fP ()"
.br
.ti -1c
.RI "const unsigned int & \fBgetFPS\fP () const "
.br
.ti -1c
.RI "void \fBsetFPS\fP (const unsigned int &FPS)"
.br
.ti -1c
.RI "void \fBcreate\fP ()"
.br
.ti -1c
.RI "void \fBpoll\fP ()"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "const int \fBgetOriginalWidth\fP () const "
.br
.ti -1c
.RI "const int \fBgetOriginalHeight\fP () const "
.br
.ti -1c
.RI "std::string \fBgetTitle\fP ()"
.br
.ti -1c
.RI "const std::string \fBgetTitle\fP () const "
.br
.ti -1c
.RI "void \fBsetTitle\fP (const std::string &newTitle)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBfps\fP = 0"
.br
.ti -1c
.RI "GLFWwindow * \fBwindow\fP"
.br
.ti -1c
.RI "int \fBoriginalWidth\fP"
.br
.ti -1c
.RI "int \fBoriginalHeight\fP"
.br
.ti -1c
.RI "std::string \fBtitle\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBWindowModule\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file Window\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::os::Window::Window (const int width, const int height, const char * title)"

.SH "Member Function Documentation"
.PP 
.SS "void mc::os::Window::create ()"

.SS "void mc::os::Window::destroy ()"

.SS "const unsigned int& mc::os::Window::getFPS () const"

.SS "GLFWwindow* mc::os::Window::getGLFWWindow ()"

.SS "const int mc::os::Window::getOriginalHeight () const"

.SS "const int mc::os::Window::getOriginalWidth () const"

.SS "std::string mc::os::Window::getTitle ()"

.SS "const std::string mc::os::Window::getTitle () const"

.SS "void mc::os::Window::poll ()"

.SS "void mc::os::Window::setFPS (const unsigned int & FPS)"

.SS "void mc::os::Window::setTitle (const std::string & newTitle)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBWindowModule\fP\fC [friend]\fP"

.PP
Definition at line 32 of file Window\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int mc::os::Window::fps = 0\fC [protected]\fP"

.PP
Definition at line 51 of file Window\&.h\&.
.SS "int mc::os::Window::originalHeight\fC [protected]\fP"

.PP
Definition at line 55 of file Window\&.h\&.
.SS "int mc::os::Window::originalWidth\fC [protected]\fP"

.PP
Definition at line 54 of file Window\&.h\&.
.SS "std::string mc::os::Window::title\fC [protected]\fP"

.PP
Definition at line 56 of file Window\&.h\&.
.SS "GLFWwindow* mc::os::Window::window\fC [protected]\fP"

.PP
Definition at line 53 of file Window\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
