.TH "mc::os" 3 "Wed Feb 1 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::os \- Namespace with functions related to the operating system like keyboard input, mouse, and windows\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBInput\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowModule\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::tm * \fBlocaltime\fP (std::tm *result, const std::time_t *time)"
.br
.ti -1c
.RI "std::tm * \fBgmtime\fP (std::tm *result, const std::time_t *time)"
.br
.ti -1c
.RI "char * \fBctime\fP (char *buffer, std::size_t bufSize, const std::time_t *time)"
.br
.ti -1c
.RI "char * \fBasctime\fP (char *buffer, std::size_t bufSize, const std::tm *time)"
.br
.ti -1c
.RI "FILE * \fBfopen\fP (FILE **result, const char *filename, const char *mode)"
.br
.ti -1c
.RI "std::size_t \fBmbsrtowcs\fP (std::size_t *returnValue, wchar_t *wcstr, std::size_t sizeInWords, const char **mbstr, std::size_t count, mbstate_t *mbstate)"
.br
.ti -1c
.RI "void \fBassert\fP (const bool cond, const std::string &message)"
.br
.ti -1c
.RI "void \fBassert\fP (const bool cond, const char *message='Assertion failed')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Namespace with functions related to the operating system like keyboard input, mouse, and windows\&. 

Also contains cross-platform safer versions of many std functions\&.
.PP
\fBTodo\fP
.RS 4
Add function for pausing the console 
.PP
Add memory functions like memcpy and memmove 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "char* mc::os::asctime (char * buffer, std::size_t bufSize, const std::tm * time)"

.SS "void mc::os::assert (const bool cond, const std::string & message)"

.SS "void mc::os::assert (const bool cond, const char * message = \fC'Assertion failed'\fP)"

.SS "char* mc::os::ctime (char * buffer, std::size_t bufSize, const std::time_t * time)"

.SS "FILE* mc::os::fopen (FILE ** result, const char * filename, const char * mode)"

.SS "std::tm* mc::os::gmtime (std::tm * result, const std::time_t * time)"

.SS "std::tm* mc::os::localtime (std::tm * result, const std::time_t * time)"

.SS "std::size_t mc::os::mbsrtowcs (std::size_t * returnValue, wchar_t * wcstr, std::size_t sizeInWords, const char ** mbstr, std::size_t count, mbstate_t * mbstate)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
