.TH "mc::os" 3 "Fri Nov 25 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::os \- Namespace with classes related to the operating system like keyboard input, mouse, and windows\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBInput\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphicsContext\fP"
.br
.ti -1c
.RI "class \fBWindow\fP"
.br
.ti -1c
.RI "class \fBWindowModule\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Namespace with classes related to the operating system like keyboard input, mouse, and windows\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
