.TH "mc::Process" 3 "Sat Apr 8 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::Process \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Process\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcess\fP ()"
.br
.ti -1c
.RI "\fBProcess\fP (const char *path, char *args)"
.br
.ti -1c
.RI "\fBProcess\fP (const std::string &path, std::string &args)"
.br
.ti -1c
.RI "\fB~Process\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP (const char *path, char *args)"
.br
.ti -1c
.RI "void \fBinit\fP (const std::string &path, std::string &args)"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "int \fBwait\fP ()"
.br
.ti -1c
.RI "bool \fBisRunning\fP () const "
.br
.ti -1c
.RI "bool \fBisCreated\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file Process\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::Process::Process ()"

.SS "mc::Process::Process (const char * path, char * args)"

.SS "mc::Process::Process (const std::string & path, std::string & args)"

.SS "mc::Process::~Process ()"

.SH "Member Function Documentation"
.PP 
.SS "void mc::Process::destroy ()"

.SS "void mc::Process::init (const char * path, char * args)"

.SS "void mc::Process::init (const std::string & path, std::string & args)"

.SS "bool mc::Process::isCreated () const"

.SS "bool mc::Process::isRunning () const"

.SS "int mc::Process::wait ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
