.TH "mc::Sound" 3 "Sat Apr 8 2017" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mc::Sound \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Audio\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBProperties\fP : Byte { \fBLOOPING\fP = 0 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSound\fP (const std::string &path)"
.br
.ti -1c
.RI "void \fBplay\fP ()"
.br
.ti -1c
.RI "void \fBpause\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBsetVolume\fP (float volume)"
.br
.ti -1c
.RI "float \fBgetVolume\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.ti -1c
.RI "bool \fBgetProperty\fP (const \fBByte\fP param) const "
.br
.ti -1c
.RI "void \fBsetProperty\fP (const \fBByte\fP param, const bool value)"
.br
.ti -1c
.RI "void \fBsetLooping\fP (const bool val)"
.br
.ti -1c
.RI "bool \fBisLooping\fP () const "
.br
.ti -1c
.RI "void \fBsetProperties\fP (const \fBBitField\fP &b)"
.br
.ti -1c
.RI "\fBBitField\fP & \fBgetProperties\fP ()"
.br
.ti -1c
.RI "const \fBBitField\fP & \fBgetProperties\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file Audio\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBmc::Sound::Properties\fP : \fBByte\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILOOPING \fP\fP
.PP
Definition at line 35 of file Audio\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mc::Sound::Sound (const std::string & path)"

.SH "Member Function Documentation"
.PP 
.SS "void mc::Sound::destroy ()"

.SS "\fBBitField\fP& mc::Sound::getProperties ()"

.SS "const \fBBitField\fP& mc::Sound::getProperties () const"

.SS "bool mc::Sound::getProperty (const \fBByte\fP param) const"

.SS "float mc::Sound::getVolume ()\fC [inline]\fP"

.PP
Definition at line 46 of file Audio\&.h\&.
.SS "void mc::Sound::init ()"

.SS "bool mc::Sound::isLooping () const"

.SS "void mc::Sound::pause ()"

.SS "void mc::Sound::play ()"

.SS "void mc::Sound::setLooping (const bool val)"

.SS "void mc::Sound::setProperties (const \fBBitField\fP & b)"

.SS "void mc::Sound::setProperty (const \fBByte\fP param, const bool value)"

.SS "void mc::Sound::setVolume (float volume)"

.SS "void mc::Sound::stop ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for MACE from the source code\&.
