.TH "md__i_n_s_t_a_l_l_a_t_i_o_n" 3 "Sun Dec 11 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__i_n_s_t_a_l_l_a_t_i_o_n \- Installation 

.IP "\(bu" 2
Download the MACE source\&.
.IP "  \(bu" 4
This can be done via Git: Type \fCgit clone https://github.com/liavt/mace.git\fP in terminal\&. On Windows, you will need MingW or a similar Unix emulator
.IP "  \(bu" 4
You can also use the Git GUI if you don't like command line\&.
.PP

.IP "\(bu" 2
Download CMake
.IP "  \(bu" 4
On Windows systems, make sure to add it to your Path\&.
.PP

.IP "\(bu" 2
Create a new folder called build in the MACE source directory
.IP "\(bu" 2
Open the terminal\&.
.IP "  \(bu" 4
On Windows systems, open the standard command prompt\&.
.PP

.IP "\(bu" 2
Type \fCcd <path to where you downloaded the MACE source>\fP
.IP "  \(bu" 4
On Windows, you may need to change to the drive via \fCcd \\d <drive letter>\fP
.PP

.IP "\(bu" 2
Type \fCcd build\fP
.IP "\(bu" 2
Finally, type \fCcmake \&.\&.\fP
.IP "  \(bu" 4
You will need an internet connection for this step\&.
.PP

.IP "\(bu" 2
You should now be installing MACE!
.IP "\(bu" 2
If you are on Windows, a Visual Studio solution file should have been generated\&. Open it to find all of the source code linked and ready!
.IP "  \(bu" 4
To build MACE, simply use Visual Studio to build the ALL-BUILD project
.PP

.IP "\(bu" 2
If you are on OSX, you will have a choice of generating a Makefile or an XCode project
.IP "\(bu" 2
If you are on Linux, you will have a Makefile generated for you\&. Simply type \fCmake <path to makefile>\fP to compile it via GCC 
.PP

