.TH "todo" 3 "Sat Dec 17 2016" "Version Alpha" "MACE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBNamespace \fBmc::gfx\fP \fP" 1c
create a ReadableBuffer class with functions like glReadPixels  
.IP "\fBMember \fBmc::gfx::ogl::FrameBuffer::attachTexture\fP (const GLenum &target, const GLenum &attachment, const GLuint &textureID, const GLint &level=0)\fP" 1c
Replace this with the actual \fBTexture\fP class  
.IP "\fBClass \fBmc::gfx::ogl::Object\fP \fP" 1c
create an RAII wrapper which calls \fBinit()\fP and \fBdestroy()\fP automatically  
.IP "\fBClass \fBmc::Preprocessor\fP \fP" 1c
Digraphs (see 6\&.4\&.6 of standard) 
.PP
Variable arguments 
.PP
\fBMacro\fP concat 
.PP
\fC#if and\fP#elif` 
.PP
\fC#pragma\fP (if STDC follows, do no macro replacement) 
.PP

