/*
The MIT License (MIT)

Copyright (c) 2016 Liav Turkia

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*/
#pragma once
#ifndef MACE_GRAPHICS_SHADERS_H
#define MACE_GRAPHICS_SHADERS_H

#include <MACE/Utility/Matrix.h>
#include <unordered_map>
#include <GL/glew.h>


namespace mc {
	namespace gfx {

		/**
		@todo make a shader class
		*/
		class ShaderProgram {
		public:
			ShaderProgram();
			~ShaderProgram();

			void init();
			void destroy();

			void bind() const;
			void unbind() const;

			void createFragment(const char shader[]);
			void createFragment(const std::string& shader);
			void createVertex(const char shader[]);
			void createVertex(const std::string& shader);

			void createUniform(const std::string& name);
			void createUniform(const char* name);

			int getUniformLocation(const std::string& name);
			int getUniformLocation(const char* name);

			int getProgramID() const;
			int getVertexID() const;
			int getFragmentID() const;

			//dont worry. these functions are all autogenerated
			//setUniform with float matrices
			void setUniform(char * name, const bool transpose, const mc::Matrix<float, 2, 2>& m) { float flattenedData[2 * 2]; __glewUniformMatrix2fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 2, 2>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<float, 3, 3>& m) { float flattenedData[3 * 3]; __glewUniformMatrix3fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 3, 3>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<float, 4, 4>& m) { float flattenedData[4 * 4]; __glewUniformMatrix4fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 4, 4>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<float, 2, 3>& m) { float flattenedData[2 * 3]; __glewUniformMatrix2x3fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 2, 3>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<float, 3, 2>& m) { float flattenedData[3 * 2]; __glewUniformMatrix3x2fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 3, 2>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<float, 2, 4>& m) { float flattenedData[2 * 4]; __glewUniformMatrix2x4fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 2, 4>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<float, 3, 4>& m) { float flattenedData[3 * 4]; __glewUniformMatrix3x4fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 3, 4>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<float, 4, 3>& m) { float flattenedData[4 * 3]; __glewUniformMatrix4x3fv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<float, 4, 3>& m) { setUniform(name, true, m); };;
			//setUniform with double matrices
			void setUniform(char * name, const bool transpose, const mc::Matrix<double, 2, 2>& m) { double flattenedData[2 * 2]; __glewUniformMatrix2dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 2, 2>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<double, 3, 3>& m) { double flattenedData[3 * 3]; __glewUniformMatrix3dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 3, 3>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<double, 4, 4>& m) { double flattenedData[4 * 4]; __glewUniformMatrix4dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 4, 4>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<double, 2, 3>& m) { double flattenedData[2 * 3]; __glewUniformMatrix2x3dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 2, 3>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<double, 3, 2>& m) { double flattenedData[3 * 2]; __glewUniformMatrix3x2dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 3, 2>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<double, 2, 4>& m) { double flattenedData[2 * 4]; __glewUniformMatrix2x4dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 2, 4>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<double, 3, 4>& m) { double flattenedData[3 * 4]; __glewUniformMatrix3x4dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 3, 4>& m) { setUniform(name, true, m); }; void setUniform(char * name, const bool transpose, const mc::Matrix<double, 4, 3>& m) { double flattenedData[4 * 3]; __glewUniformMatrix4x3dv(uniforms[name], 1, transpose, m.flatten(flattenedData)); } void setUniform(char * name, const mc::Matrix<double, 4, 3>& m) { setUniform(name, true, m); };;

			//setUniform with float
			void setUniform(char * name, const float a) { __glewUniform1f(uniforms[name], a); } void setUniform(char * name, const float a, const float b) { __glewUniform2f(uniforms[name], a, b); } void setUniform(char * name, const float a, const float b, const float c) { __glewUniform3f(uniforms[name], a, b, c); } void setUniform(char * name, const float a, const float b, const float c, const float d) { __glewUniform4f(uniforms[name], a, b, c, d); }; void setUniform(char * name, const Size arraySize, const float* a) { __glewUniform1fv(uniforms[name], arraySize, a); } void setUniform(char * name, const Size componentSize, const Size arraySize, const float* a) { if( componentSize == 1 ) __glewUniform1fv(uniforms[name], arraySize, a); else if( componentSize == 2 ) __glewUniform2fv(uniforms[name], arraySize, a); else if( componentSize == 3 ) __glewUniform3fv(uniforms[name], arraySize, a); else if( componentSize == 4 ) __glewUniform4fv(uniforms[name], arraySize, a); }; void setUniform(char * name, const mc::Vector<float, 1> v) { __glewUniform1f(uniforms[name], v[0]); } void setUniform(char * name, const mc::Vector<float, 2> v) { __glewUniform2f(uniforms[name], v[0], v[1]); } void setUniform(char * name, const mc::Vector<float, 3> v) { __glewUniform3f(uniforms[name], v[0], v[1], v[2]); } void setUniform(char * name, const mc::Vector<float, 4> v) { __glewUniform4f(uniforms[name], v[0], v[1], v[2], v[3]); };;
			//setUniform with double
			void setUniform(char * name, const double a) { __glewUniform1d(uniforms[name], a); } void setUniform(char * name, const double a, const double b) { __glewUniform2d(uniforms[name], a, b); } void setUniform(char * name, const double a, const double b, const double c) { __glewUniform3d(uniforms[name], a, b, c); } void setUniform(char * name, const double a, const double b, const double c, const double d) { __glewUniform4d(uniforms[name], a, b, c, d); }; void setUniform(char * name, const Size arraySize, const double* a) { __glewUniform1dv(uniforms[name], arraySize, a); } void setUniform(char * name, const Size componentSize, const Size arraySize, const double* a) { if( componentSize == 1 ) __glewUniform1dv(uniforms[name], arraySize, a); else if( componentSize == 2 ) __glewUniform2dv(uniforms[name], arraySize, a); else if( componentSize == 3 ) __glewUniform3dv(uniforms[name], arraySize, a); else if( componentSize == 4 ) __glewUniform4dv(uniforms[name], arraySize, a); }; void setUniform(char * name, const mc::Vector<double, 1> v) { __glewUniform1d(uniforms[name], v[0]); } void setUniform(char * name, const mc::Vector<double, 2> v) { __glewUniform2d(uniforms[name], v[0], v[1]); } void setUniform(char * name, const mc::Vector<double, 3> v) { __glewUniform3d(uniforms[name], v[0], v[1], v[2]); } void setUniform(char * name, const mc::Vector<double, 4> v) { __glewUniform4d(uniforms[name], v[0], v[1], v[2], v[3]); };;
			//setUniform with int
			void setUniform(char * name, const int a) { __glewUniform1i(uniforms[name], a); } void setUniform(char * name, const int a, const int b) { __glewUniform2i(uniforms[name], a, b); } void setUniform(char * name, const int a, const int b, const int c) { __glewUniform3i(uniforms[name], a, b, c); } void setUniform(char * name, const int a, const int b, const int c, const int d) { __glewUniform4i(uniforms[name], a, b, c, d); }; void setUniform(char * name, const Size arraySize, const int* a) { __glewUniform1iv(uniforms[name], arraySize, a); } void setUniform(char * name, const Size componentSize, const Size arraySize, const int* a) { if( componentSize == 1 ) __glewUniform1iv(uniforms[name], arraySize, a); else if( componentSize == 2 ) __glewUniform2iv(uniforms[name], arraySize, a); else if( componentSize == 3 ) __glewUniform3iv(uniforms[name], arraySize, a); else if( componentSize == 4 ) __glewUniform4iv(uniforms[name], arraySize, a); }; void setUniform(char * name, const mc::Vector<int, 1> v) { __glewUniform1i(uniforms[name], v[0]); } void setUniform(char * name, const mc::Vector<int, 2> v) { __glewUniform2i(uniforms[name], v[0], v[1]); } void setUniform(char * name, const mc::Vector<int, 3> v) { __glewUniform3i(uniforms[name], v[0], v[1], v[2]); } void setUniform(char * name, const mc::Vector<int, 4> v) { __glewUniform4i(uniforms[name], v[0], v[1], v[2], v[3]); };;
			//setUniform with unsigned int
			void setUniform(char * name, const unsigned int a) { __glewUniform1ui(uniforms[name], a); } void setUniform(char * name, const unsigned int a, const unsigned int b) { __glewUniform2ui(uniforms[name], a, b); } void setUniform(char * name, const unsigned int a, const unsigned int b, const unsigned int c) { __glewUniform3ui(uniforms[name], a, b, c); } void setUniform(char * name, const unsigned int a, const unsigned int b, const unsigned int c, const unsigned int d) { __glewUniform4ui(uniforms[name], a, b, c, d); }; void setUniform(char * name, const Size arraySize, const unsigned int* a) { __glewUniform1uiv(uniforms[name], arraySize, a); } void setUniform(char * name, const Size componentSize, const Size arraySize, const unsigned int* a) { if( componentSize == 1 ) __glewUniform1uiv(uniforms[name], arraySize, a); else if( componentSize == 2 ) __glewUniform2uiv(uniforms[name], arraySize, a); else if( componentSize == 3 ) __glewUniform3uiv(uniforms[name], arraySize, a); else if( componentSize == 4 ) __glewUniform4uiv(uniforms[name], arraySize, a); }; void setUniform(char * name, const mc::Vector<unsigned int, 1> v) { __glewUniform1ui(uniforms[name], v[0]); } void setUniform(char * name, const mc::Vector<unsigned int, 2> v) { __glewUniform2ui(uniforms[name], v[0], v[1]); } void setUniform(char * name, const mc::Vector<unsigned int, 3> v) { __glewUniform3ui(uniforms[name], v[0], v[1], v[2]); } void setUniform(char * name, const mc::Vector<unsigned int, 4> v) { __glewUniform4ui(uniforms[name], v[0], v[1], v[2], v[3]); };;

		private:
			int id = -1;
			int fragId = -1, vertId = -1;

			std::unordered_map<std::string, int> uniforms = std::unordered_map<std::string, int>();

			int createShader(const char code[], const GLenum& type);

			void createProgram();

		};//ShaderProgram

	}//gfx
}//mc

#endif